CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_TRANSACCIONES_COMPRAS()
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_TRANSACCIONES_COMPRAS PARTITION BY
   DATE(FH_ORDEN_SINFORMATO)   
	 AS
	/**************************** Tabla de hechos del modulo de compras, aca se relacionan las tablas requeridas de la capa RAW y las llaves necesarias para crear la tabla consolodada en en la capa de presentacion, se consolida la informacion de las ordenes de compra de indirectos, ordenes y contratos a nivel de lineas y distribuciones  ***************************/
		SELECT 
			707 APPLICATIONID,
			ATL2.APTERMSLINESDUEDAYS		AS COND_PAGO_PROV,
			PLA.UNITPRICE 							AS VR_UNIT_ORDEN,
			PLA.QUANTITY 								AS CANTIDAD,
			PLA.AMOUNT 									AS VR_ORDEN,
			SHA256(CAST(PO_H.POHEADERID AS STRING)) AS SK_POHEADERID,
			SHA256(CAST(PLA.POLINEID AS STRING)) AS ASSK_POLINEID,
			PDA.NONRECOVERABLETAX 			AS IMP_ORDEN,
			PO_H.TYPELOOKUPCODE 				AS TIP_ORD,
			PO_H.DOCUMENTSTATUS 				AS EST_DOC_ORD,
			PO_H.COMMENTS 							AS DESC_ORD,
			PO_H.SEGMENT1 							AS ORDEN_COMPRA,
			PO_H.CREATIONDATE 					AS FH_ORDEN,
			PO_H.APPROVEDDATE 					AS FH_APROB_ORD,
			PO_H.CREATIONDATE 					AS FH_ORDEN_SINFORMATO,
			PO_H.CREATEDBY 							AS ORD_US_CRE,
			PO_H.COMMENTS								AS DESCRIPCION,
			SHA256(CAST(RCVT.RCVNGRCPTTRNSCTNEXTRCTPEOPODISTRIBUTIONID AS STRING))  AS SK_PODISTRIBUTIONID,
			SHA256(CAST(RCVT.RCVNGRCPTTRNSCTNEXTRCTPEOTRANSACTIONID AS STRING)) 		AS SK_TRANSACTIONID,
			SHA256(CAST(PO_H.VENDORID AS STRING))					AS SK_TERCERO,
			RCVT.RCVNGRCPTTRNSCTNEXTRCTPEOTRANSACTIONTYPE AS TRANSACTIONTYPE,
			PRH.REQUISITIONNUMBER AS NUM_SOLICITUD,
			PRH.CREATIONDATE 			AS FH_CRESOL,
			PRH.DOCUMENTSTATUS	  AS ESTADO_SOL,
			PRH.CREATEDBY 				AS SOL_CREADAPOR
		FROM 
				amrl-data-prd.RAW.FUSION_PO_HEADERS_ALL AS PO_H 
				LEFT JOIN amrl-data-prd.RAW.FUSION_AP_TERMS_LINES AS ATL2 ON PO_H.TERMSID = ATL2.APTERMSLINESTERMID
				LEFT JOIN amrl-data-prd.RAW.FUSION_PO_LINES_ALL AS PLA ON PO_H.POHEADERID = PLA.POHEADERID 
				LEFT JOIN amrl-data-prd.RAW.FUSION_PO_DISTRIBUTIONS_ALL AS PDA ON PDA.POHEADERID = PLA.POHEADERID AND PLA.POLINEID = PDA.POLINEID
				LEFT JOIN amrl-data-prd.RAW.FUSION_RCV_TRANSACTIONS AS RCVT ON PDA.PODISTRIBUTIONID = RCVT.RCVNGRCPTTRNSCTNEXTRCTPEOPODISTRIBUTIONID
				LEFT JOIN amrl-data-prd.RAW.FUSION_POR_REQUISITION_LINES_ALL AS PRL ON PRL.POHEADERID = PLA.POHEADERID AND PRL.POLINEID = PLA.POLINEID
				LEFT JOIN amrl-data-prd.RAW.FUSION_POR_REQUISITION_HEADERS_ALL AS PRH ON PRL.REQUISITIONHEADERID = PRH.REQUISITIONHEADERID ;
	END;