CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_OBT_FACT_MOVIMIENTO_DETALLADO()
OPTIONS(
  description=" Informacion del balance detallado por segmento y tercero, muestra la informacion agrupada por tercero por periodo contable, esta consulta crea en la capa de consumo el movimiento detallado")
BEGIN
	CREATE OR REPLACE TABLE amrl-data-prd.CONSUMPTION.OBT_FACT_MOVIMIENTO_DETALLADO PARTITION BY
   FH_APERTURA_PER CLUSTER BY PERIODO,NOMBRE_TERCERO, NIVEL_4, PROYECTO AS 
	 /**************************** Informacion del balance detallado por segmento y tercero, muestra la informacion de manera detallada por cada una de las lineas y distribuciones aca se consolida las tablas de hechos y dimensiones requeridas para construir la tabla de consumo de movimiento detallado ***************************/
	SELECT  
		COMPANIA,	
		NOMBRE_COMPANIA,	
		NIVEL_1,	
		NOMBRE_NVL1,	
		NIVEL_2,	
		NOMBRE_NVL2,	
		NIVEL_3,	
		NOMBRE_NVL3,	
		NIVEL_4,	
		NOMBRE_NVL4,	
		NIVEL_5,	
		NOMBRE_NVL5,	
		NIVEL_6,	
		NOMBRE_NVL6,	
		NIVEL_7,	
		NOMBRE_NVL7,	
		NIVEL_8,	
		NOMBRE_NVL8,	
		NIVEL_9,	
		NOMBRE_NVL9,	
		NIVEL_10,	
		NOMBRE_NVL10,	
		CUENTA,	
		NOMBRE_CUENTA,	
		GRUPO,	
		NOMBRE_GRUPO,	
		CONSOLIDADOR,	
		DES_CONSOLIDADOR,	
		PROYECTO,	
		NOMBRE_PROYECTO,	
		AREA,	
		NOMBRE_AREA,	
		FUTURO,	
		NOMBRE_FUTURO,	
		SK_COMBINATION_ID,	
		LIBRO,	
		NIT,	
		MAX(NOMBRE_TERCERO) OVER (PARTITION BY NIT) AS NOMBRE_TERCERO,	
		NIT_CABECERA,	
		MAX(TERCERO_CABECERA) OVER (PARTITION BY NIT_CABECERA) AS TERCERO_CABECERA,	
		PERIODO,	
		FH_CONTABLE,	
		DOCUMENTO,	
		TRANSACTIONENTITYCODE,	
		ORIGEN,	
		CATEGORIA,	
		DOCUMENTO_CON,	
		CONCEPTO,	
		DESCRIPCION,	
		PERIODPERIODYEAR,	
		PERIODPERIODNUM,	
		FH_APERTURA_PER,	
		PERIODENDDATE,	
		NUM_LINEA,	
		LINEA_TEMP,	
		DEBITO,	
		CREDITO,	
		ACTIVIDAD_PERIODO
	FROM amrl-data-prd.PRESENTATION.FACT_MOVIMIENTO_DETALLADO 
	;
END;