CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_DIM_MACROPROYECTO()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla DIM_MACROPROYECTO, consolidando todos los atributos que se encuentren a nivel de Macroproyecto\nAutor: Maria Fernanda Franco")
BEGIN

CREATE TEMP TABLE TEMP_MACROPROYECTO AS
( 	
    SELECT ROW_NUMBER() OVER (ORDER BY SK_COD_MACROPROYECTO) AS ID_DIM_MACROPROYECTO
           ,T1.SK_COD_MACROPROYECTO
           ,T1.MACROPROYECTO
           ,T1.TOTAL_VIVIENDAS_MACROPROYECTO
           ,T1.TOTAL_COMERCIOS_MACROPROYECTO
           ,T1.FECHA_ULTIMA_ACTUALIZACION
           ,T1.FECHA_ACTUALIZACION_BQ
           ,T1.FECHA_CARGUE_BQ
    FROM (
            SELECT ROW_NUMBER() OVER(PARTITION BY HZRE.EXTN_ATTRIBUTE_CHAR036 ORDER BY HZRE.LAST_UPDATE_DATE DESC) AS ID,
                  HZRE.EXTN_ATTRIBUTE_CHAR036          AS SK_COD_MACROPROYECTO,
                  HZRE.EXTN_ATTRIBUTE_CHAR010          AS MACROPROYECTO,
                  HZRE.LAST_UPDATE_DATE                AS FECHA_ULTIMA_ACTUALIZACION,
                  HZRE.EXTN_ATTRIBUTE_NUMBER024		     AS TOTAL_VIVIENDAS_MACROPROYECTO, 
                  HZRE.EXTN_ATTRIBUTE_NUMBER025        AS TOTAL_COMERCIOS_MACROPROYECTO,  
                  HZRE.RECORD_NAME					           AS SK_TRANSACCIONAL,
                  CURRENT_DATETIME("America/Bogota")   AS FECHA_ACTUALIZACION_BQ,
		              CURRENT_DATETIME("America/Bogota")   AS FECHA_CARGUE_BQ 
            FROM `RAW.FUSION_HZ_REF_ENTITIES` HZRE 
    ) T1 
    WHERE T1.ID= 1 AND T1.SK_COD_MACROPROYECTO IS NOT NULL
    ORDER BY SK_COD_MACROPROYECTO

);

--CREANDO TABLA PERMANENTE
--CREATE OR REPLACE TABLE `amrl-data-prd.PRESENTATION.DIM_MACROPROYECTO` AS 
--SELECT * FROM TEMP_MACROPROYECTO;

    MERGE   PRESENTATION.DIM_MACROPROYECTO     AS T
    USING   (SELECT * FROM TEMP_MACROPROYECTO) AS S
    ON      (T.SK_COD_MACROPROYECTO = S.SK_COD_MACROPROYECTO)
    WHEN MATCHED THEN
    UPDATE SET  T.MACROPROYECTO                     = S.MACROPROYECTO,
                T.TOTAL_VIVIENDAS_MACROPROYECTO     = S.TOTAL_VIVIENDAS_MACROPROYECTO,
                T.TOTAL_COMERCIOS_MACROPROYECTO     = S.TOTAL_COMERCIOS_MACROPROYECTO,
                T.FECHA_ULTIMA_ACTUALIZACION        = S.FECHA_ULTIMA_ACTUALIZACION,
                T.FECHA_ACTUALIZACION_BQ            = CURRENT_DATETIME("America/Bogota")
    WHEN NOT MATCHED THEN
    INSERT  (   ID_DIM_MACROPROYECTO,
                SK_COD_MACROPROYECTO, 
                MACROPROYECTO,
                TOTAL_VIVIENDAS_MACROPROYECTO,               
                TOTAL_COMERCIOS_MACROPROYECTO,
                FECHA_ULTIMA_ACTUALIZACION,
                FECHA_ACTUALIZACION_BQ,
                FECHA_CARGUE_BQ
            )
    VALUES (    S.ID_DIM_MACROPROYECTO,
                S.SK_COD_MACROPROYECTO, 
                S.MACROPROYECTO,
                S.TOTAL_VIVIENDAS_MACROPROYECTO,               
                S.TOTAL_COMERCIOS_MACROPROYECTO,
                S.FECHA_ULTIMA_ACTUALIZACION,
                S.FECHA_ACTUALIZACION_BQ,
                S.FECHA_CARGUE_BQ
            );

END;