CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FUSION_RA_CUSTOMER_TRX_LINES_ALL_DELETED()
BEGIN
  -- Step 1: Crear una tabla temporal con los RACUSTOMERTRXLINECUSTOMERTRXLINEID de RAW.RA_CUSTOMER_TRX_LINES_ALL que no están en STAGING.RA_CUSTOMER_TRX_LINES_ALL_PK
  CREATE TEMP TABLE ids_a_actualizar4 AS
  SELECT
    line.RACUSTOMERTRXLINECUSTOMERTRXLINEID
  FROM
    `amrl-data-prd.RAW.FUSION_RA_CUSTOMER_TRX_LINES_ALL` AS line
  LEFT JOIN
    `amrl-data-prd.STAGING.FUSION_RA_CUSTOMER_TRX_LINES_ALL_PK` AS line_pk
  ON
    line.RACUSTOMERTRXLINECUSTOMERTRXLINEID = line_pk.RACUSTOMERTRXLINECUSTOMERTRXLINEID
  WHERE
    line_pk.RACUSTOMERTRXLINECUSTOMERTRXLINEID IS NULL;

  -- Step 2: Actualizar la columna DELETED en la tabla RAW.RA_CUSTOMER_TRX_LINES_ALL para los registros que están en la tabla temporal
  UPDATE
    `amrl-data-prd.RAW.FUSION_RA_CUSTOMER_TRX_LINES_ALL`
  SET
    DELETED = '1'
  WHERE
    RACUSTOMERTRXLINECUSTOMERTRXLINEID IN (SELECT RACUSTOMERTRXLINECUSTOMERTRXLINEID FROM ids_a_actualizar4);

  -- Step 3: Limpiar la tabla temporal
  DROP TABLE ids_a_actualizar4;
END;