CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_CUENTAS_A_PAGAR_PAGOS()
OPTIONS(
  description="Información del modulo cuentas a pagar -  Pagos")
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_CUENTAS_A_PAGAR_PAGOS PARTITION BY
   FECHA_PAGO   AS 
/**************************** Informacion transacciones de Cuentas por Pagar - Pagos - informacion a nivel de los pagos, contiene la informacion, detalle de la cabecer de pagos y la relacion con la facturacion ***************************/
			SELECT 
				200 APPLICATIONID,
				'AP_PAYMENTS' AS ORIGEN,
				SHA256(CAST(APA.APINVOICEPAYMENTSALLINVOICEID AS STRING))  AS SK_INVOICEID,
				APA.APINVOICEPAYMENTSALLINVOICEPAYMENTTYPE                 AS PAYMENTTYPE,
				APA.APINVOICEPAYMENTSALLAMOUNT                             AS LINEA_PAGO,
				APA.APINVOICEPAYMENTSALLACCOUNTINGDATE                     AS  FH_CONTABLE,
				APA.APINVOICEPAYMENTSALLREVERSALFLAG,                     
				SHA256(CAST(FAC.APCHECKSALLCHECKID AS STRING))             AS SK_CHECKID,
				FAC.APCHECKSALLADDRESSLINE1,
				FAC.APCHECKSALLAMOUNT 							AS PAGO_CAB,
				FAC.APCHECKSALLBANKACCOUNTNAME,
				FAC.APCHECKSALLCHECKDATE 						AS FECHA_PAGO,
				FAC.APCHECKSALLCHECKNUMBER  				AS NUM_PAGO,
				FAC.APCHECKSALLPAYMENTMETHODCODE 		AS METODO_PAGO,
				FAC.APCHECKSALLSTATUSLOOKUPCODE 		AS ESTADO_PAGO,
					SHA256(CAST(CASE 
										WHEN CAST(FAC.APCHECKSALLVENDORID AS STRING) LIKE '%-%' THEN FAC.APCHECKSALLPARTYID 
										ELSE FAC.APCHECKSALLVENDORID 
								END AS STRING)) AS SK_TERCERO


			from amrl-data-prd.RAW.FUSION_AP_CHECKS_ALL FAC
			LEFT JOIN amrl-data-prd.RAW.FUSION_AP_INVOICE_PAYMENTS_ALL APA ON APA.APINVOICEPAYMENTSALLCHECKID =FAC.APCHECKSALLCHECKID;
			END;