CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_GESTION_DE_EFECTIVO()
OPTIONS(
  description="Información del modulo gestión de efectivo ")
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_GESTION_DE_EFECTIVO PARTITION BY
   FH_TRANSACCION   AS 
  
		/**************************** Tabla de hechos del modulo de gestion de efectivo, aca se relacionan las tablas requeridas de la capa RAW y las llaves necesarias para crear la tabla consolodada en en la capa de presentacion, se relaciona la informacion de las cuentas bancarias y transacciones    ***************************/
		SELECT
			260 APPLICATIONID,
			'CE_EXTERNAL'  ORIGEN,
			SHA256(CAST(CET.EXTERNALTRANSACTIONSTRANSACTIONID AS STRING)) AS SK_IDORIGEN,
			CET.EXTERNALTRANSACTIONSTRANSACTIONID AS BK_IDORIGEN,
			SHA256(CAST(CBA.BANKACCOUNTREPORTPEOBANKID AS STRING)) AS SK_TERCERO,
			CBA.BANKACCOUNTREPORTPEOBANKID AS BK_TERCERO,
			CBA.BANKACCOUNTREPORTPEOBANKACCOUNTNUM AS DOCUMENTO,
			CET.EXTERNALTRANSACTIONSTRANSACTIONDATE AS FH_TRANSACCION
		FROM  amrl-data-prd.RAW.FUSION_CE_EXTERNAL_TRANSACTIONS CET 
			LEFT JOIN  amrl-data-prd.RAW.FUSION_CE_BANK_ACCOUNTS CBA ON CBA.BANKACCOUNTREPORTPEOBANKACCOUNTID =CET.EXTERNALTRANSACTIONSBANKACCOUNTID;
END;