CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_DIM_PERIODOS()
OPTIONS(
  description="Información de los periodos contables ")
BEGIN
CREATE TEMP TABLE TEMP_DIM_PERIODOS AS 
	
(
 /**************************** Consolida la informacion de los periodos contables por nombre y por fechas ***************************/
  SELECT  
    SHA256(CAST(PERIODPERIODNAME AS STRING)) AS SK_PERIODO,
    PERIODPERIODNAME BK_PERIODO,
    PERIODSTARTDATE,
    PERIODENDDATE,
    PERIODYEARSTARTDATE,
    PERIODPERIODYEAR,
    PERIODPERIODNUM

  FROM 
    amrl-data-prd.RAW.FUSION_GL_PERIODS

  ORDER BY  
    PERIODPERIODYEAR,
    PERIODPERIODNUM

);

MERGE `amrl-data-prd.PRESENTATION.DIM_PERIODOS` AS T 
USING (SELECT * FROM TEMP_DIM_PERIODOS) AS S 
ON (T.SK_PERIODO = S.SK_PERIODO)
WHEN MATCHED THEN
UPDATE SET   
T.BK_PERIODO            = S.BK_PERIODO,
T.PERIODSTARTDATE       = S.PERIODSTARTDATE,
T.PERIODENDDATE         = S.PERIODENDDATE,
T.PERIODYEARSTARTDATE   = S.PERIODYEARSTARTDATE,
T.PERIODPERIODYEAR      = S.PERIODPERIODYEAR,
T.PERIODPERIODNUM       = S.PERIODPERIODNUM
WHEN NOT MATCHED THEN
INSERT(
  SK_PERIODO,
  BK_PERIODO,
  PERIODSTARTDATE,
  PERIODENDDATE,
  PERIODYEARSTARTDATE,
  PERIODPERIODYEAR,
  PERIODPERIODNUM
)
VALUES(
  S.SK_PERIODO,
  S.BK_PERIODO,
  S.PERIODSTARTDATE,
  S.PERIODENDDATE,
  S.PERIODYEARSTARTDATE,
  S.PERIODPERIODYEAR,
  S.PERIODPERIODNUM
);
END;