CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_EJECUCION()
BEGIN



/**********************************runSPBigquery01()*********************/
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_MOO_OPTY_CON_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_MOO_OPTY_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_MOO_REVN_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_RA_CUSTOMER_TRX_ALL_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_RA_CUSTOMER_TRX_LINES_ALL_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_RA_CUST_TRX_TYPES_ALL_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_RA_TERMS_VL_DELETED`();
CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_ZCA_SALES_ORDER_HEADERS_DELETED`();


/**********************************runSPBigquery02()*********************/
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_COBRO`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_TIEMPO`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_TRAMITES`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_PERSONAS`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_SUB_ETAPA`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_INVENTARIO`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_MACROPROYECTO`();
CALL `amrl-data-prd.OPERATIONAL.SP_DIM_MACROCONSOLIDADOR`();
CALL`amrl-data-prd.OPERATIONAL.SP_DIM_CUENTAS`();
CALL`amrl-data-prd.OPERATIONAL.SP_DIM_PERIODOS`();
CALL`amrl-data-prd.OPERATIONAL.SP_DIM_TERCEROS`();


/**********************************runSPBigquery03()*********************/
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_OPORTUNIDAD`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_ESTADO_CUENTA`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_BALANCE_GRAL`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_CUENTAS_A_COBRAR`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_CUENTAS_A_PAGAR`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_CUENTAS_A_PAGAR_PAGOS`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_GESTION_DE_EFECTIVO`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_TRANSACCIONES_COMPRAS`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_TRANSACCIONES_COMPRAS_RECEPCIONES`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_TRANSACCIONES_CUENTAS_A_COBRAR`(); 
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_DISTRIBUCIONES_CONTABLES_AUX` ();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_MOVIMIENTO_DETALLADO`();
CALL `amrl-data-prd.OPERATIONAL.SP_FACT_TRACKING_ESCRITURACION`();

/**********************************runSPBigquery04()*********************/
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_DIM_COBRO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_DIM_PROYECTO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_DIM_PERSONA`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_DIM_INVENTARIO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_OPORTUNIDAD`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_PIVOT_FACT_OPORTUNIDAD`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_DESISTIMIENTO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_ESTADO_CUENTA`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_HISTORICO_DE_VENTAS`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_MOVIMIENTO_DETALLADO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_BALANCE_DETALLADO`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_FACT_GASTOS`();
CALL `amrl-data-prd.OPERATIONAL.SP_OBT_TRACKING_ESCRITURACION`();


--13-01-2024 procedimientos con fallas, pendiente validar su funcionalidad (creados por Xertica)
--CALL `amrl-data-prd.OPERATIONAL.SP_FUSION_EGP_SYSTEM_ITEMS_B_DELETED`();


END;