CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_CUENTAS_A_PAGAR()
OPTIONS(
  description="Información del modulo cuentas a pagar -  Facturas")
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_CUENTAS_A_PAGAR PARTITION BY FH_FACTURA  AS
/**************************** Informacion transacciones de Cuentas por Pagar - Facturas - informacion a nivel de lineas y distribuciones, contiene la informacion, detalle y distribuciones de las facturas ***************************/
		SELECT 			
			200 AS APPLICATIONID,
			'AP_INVOICES'AS ORIGEN,
			SHA256(CAST(AP_I.APINVOICESINVOICEID AS STRING)) AS SK_INVOICEID,
			AP_I.APINVOICESINVOICEID 												 AS BK_INVOICEID,
			SHA256(CAST(ADIST.APINVOICEDISTRIBUTIONSINVOICEDISTRIBUTIONID AS STRING)) AS SK_DISTORIGEN,
			ADIST.APINVOICEDISTRIBUTIONSINVOICEID AS BK_DISTORIGEN,
			AP_I.APINVOICESINVOICENUM 						AS NUMERO_FACTURA,
			AP_I.APINVOICESINVOICEDATE 						AS FH_FACTURA,
			AP_I.APINVOICESINVOICEDATE 						AS FH_FACTURASINFORMATO,
			APH.APPAYMENTSCHEDULESALLDUEDATE 			AS FH_VENC,
			AP_I.APINVOICESPAYMENTSTATUSFLAG		  AS ESTADO_PAGO,
			AP_I.APINVOICESATTRIBUTE1						  AS COD_GRUP,
			AP_I.APINVOICESATTRIBUTE2 						AS COD_PROY,
			AP_I.APINVOICESATTRIBUTE3 						AS COD_AREA,
			AP_I.APINVOICESPAYGROUPLOOKUPCODE 		AS GRUPO_PAGO,
			AP_I.APINVOICESDESCRIPTION						AS DESCRIPCION,
			CASE 
					WHEN DATE_DIFF(CURRENT_DATE(), IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE), DAY) - IFNULL(ATL.APTERMSLINESDUEDAYS, 0) <= 0 THEN 'A Tiempo'
					WHEN DATE_DIFF(CURRENT_DATE(), IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE), DAY) - IFNULL(ATL.APTERMSLINESDUEDAYS, 0) > 0 THEN 'Vencida'
				END AS ESTADO_FACTURA, 
			ATL.APTERMSLINESDUEDAYS AS CONDICION_PAGO_FACT, --CONDICION DE PAGO
			DATE_DIFF(CURRENT_DATE(), IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE), DAY) - IFNULL(ATL.APTERMSLINESDUEDAYS, 0) AS  DIAS_VENCIDOS_FACT,  --DIAS VENCIDOS	
			AP_I.APINVOICESWFAPPROVALSTATUS 				AS EST_APRO, --ESTADO DE APROVACION
			AP_I.APINVOICESAPPROVALSTATUS 					AS EST_VALIDACION ,--ESTADO DE VALIDACION
			COALESCE(ADIST.APINVOICEDISTRIBUTIONSAMOUNT,APL.APINVOICELINESALLAMOUNT) AS DIST_AMOUNT,
			AP_I.APINVOICESINVOICEAMOUNT 						AS VR_FACTCAB,
			APL.APINVOICELINESALLLINETYPELOOKUPCODE,
			ADIST.APINVOICEDISTRIBUTIONSPOSTEDFLAG 	AS EST_CONT,
			APL.APINVOICELINESALLACCOUNTINGDATE 		AS FH_CONTABLE,
			SHA256(CAST(ADIST.APINVOICEDISTRIBUTIONSRCVTRANSACTIONID AS STRING)) 				 AS SK_RCVTRANSACTIONID,
			SHA256(CAST(ADIST.APINVOICEDISTRIBUTIONSPODISTRIBUTIONID AS STRING)) 				 AS SK_PODISTRIBUTIONID,
			SHA256(CAST(ADIST.APINVOICEDISTRIBUTIONSINVOICEDISTRIBUTIONID AS STRING))		 AS SK_INVOICEDISTRIBUTIONID,
			SHA256(CAST(ADIST.APINVOICEDISTRIBUTIONSCHARGEAPPLICABLETODISTID AS STRING)) AS SK_CHARGEAPPLICABLETODISTID,
			DATE_DIFF(CURRENT_DATE(), IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE), DAY) AS DIAS_FACTURA,
			IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE) AS FH_RECIBO,
			DATE_ADD(IFNULL(AP_I.APINVOICESINVOICERECEIVEDDATE, AP_I.APINVOICESGLDATE),INTERVAL CAST(ATL.APTERMSLINESDUEDAYS AS INT64) DAY) AS FECHA_VEN_CRE,
			CASE 
				WHEN STRPOS(APL.APINVOICELINESALLATTRIBUTE1, '-') > 0 THEN SUBSTR(APL.APINVOICELINESALLATTRIBUTE1, 1, STRPOS(APL.APINVOICELINESALLATTRIBUTE1, '-') - 1)
				ELSE APL.APINVOICELINESALLATTRIBUTE1  -- O el valor original si no hay guion
			END AS NIT,		
			SHA256(CAST(CASE 
										WHEN CAST(AP_I.APINVOICESVENDORID AS STRING) LIKE '%-%' THEN AP_I.APINVOICESPARTYID 
										ELSE AP_I.APINVOICESVENDORID 
									END AS STRING)) AS SK_TERCERO,
			CASE 
				WHEN CAST(AP_I.APINVOICESVENDORID AS STRING) LIKE '%-%' THEN AP_I.APINVOICESPARTYID 
				ELSE AP_I.APINVOICESVENDORID 
			END AS BK_TERCERO

		FROM amrl-data-prd.RAW.FUSION_AP_INVOICES_ALL AS AP_I
			LEFT JOIN amrl-data-prd.RAW.FUSION_AP_INVOICE_LINES_ALL AS APL ON AP_I.APINVOICESINVOICEID = APL.APINVOICELINESALLINVOICEID
			LEFT  JOIN amrl-data-prd.RAW.FUSION_AP_INVOICE_DISTRIBUTIONS_ALL AS ADIST ON ADIST.APINVOICEDISTRIBUTIONSINVOICEID = APL.APINVOICELINESALLINVOICEID AND ADIST.APINVOICEDISTRIBUTIONSAMOUNT !=0 AND ADIST.APINVOICEDISTRIBUTIONSINVOICELINENUMBER= APL.APINVOICELINESALLLINENUMBER
			LEFT JOIN amrl-data-prd.RAW.FUSION_AP_TERMS_LINES AS ATL ON AP_I.APINVOICESTERMSID = ATL.APTERMSLINESTERMID
			LEFT JOIN amrl-data-prd.RAW.FUSION_AP_PAYMENT_SCHEDULES_ALL AS APH ON AP_I.APINVOICESINVOICEID = APH.APPAYMENTSCHEDULESALLINVOICEID;

END;