CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_DISTRIBUCIONES_CONTABLES_AUX()
OPTIONS(
  description="Contiene la información a nivel de líneas y distribuciones contables de los módulos transaccionales  ")
BEGIN
	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_DISTRIBUCIONES_CONTABLES_AUX PARTITION BY
   FH_CONTABLE CLUSTER BY DOCUMENTO ,ENTITYCODE, APPLICATIONID,PARTYID
	  AS 
	/**************************** Tabla de hechos de los sublibros contables, aca se relacionan las tablas requeridas de la capa RAW y las llaves necesarias para crear la tabla consolidada en en la capa de presentacion, contiene informacion a detalle de los registros de los modulos transaccionales a nivel contable  ***************************/
SELECT 
	SHA256(CAST(GIR.GLIMPORTREFERENCESJEHEADERID AS STRING)) SK_JEHEADERID,
	GIR.GLIMPORTREFERENCESJELINENUM JELINENUM,
	SHA256(CAST(XDL.JOURNALENTRYDISTRIBUTIONSOURCEDISTRIBUTIONIDNUM1 AS STRING)) SK_SOURCEDISTRIBUTIONIDNUM1,
	SHA256(CAST(XAL.JOURNALENTRYLINECODECOMBINATIONID AS STRING))   SK_CODECOMBINATIONID,
	XDL.JOURNALENTRYDISTRIBUTIONROUNDINGCLASSCODE CLASSCODE,
	XDL.JOURNALENTRYDISTRIBUTIONALLOCTOENTITYCODE ENTITYCODE,  
	SHA256(CAST(XDL.JOURNALENTRYDISTRIBUTIONEVENTID AS STRING)) SK_EVENTID,
	XTE.TRANSACTIONTRANSACTIONNUMBER DOCUMENTO,
	XTE.TRANSACTIONENTITYCODE,
	XAL.JOURNALENTRYLINEAPPLICATIONID APPLICATIONID,
	SHA256(CAST((XTE.TRANSACTIONSOURCEIDINT1) AS STRING)) SK_SOURCEIDINT1,
	SHA256(CAST(XAL.JOURNALENTRYLINEPARTYID AS STRING)) SK_TERCERO,
	XAL.JOURNALENTRYLINEPARTYID PARTYID,
	XAL.JOURNALENTRYLINEDESCRIPTION DESCRIPCION,
	ROUND((CASE WHEN XDL.JOURNALENTRYDISTRIBUTIONAEHEADERID IS NOT NULL THEN ROUND((IFNULL(XDL.JOURNALENTRYDISTRIBUTIONUNROUNDEDACCOUNTEDDR,0)),2)  ELSE (CASE WHEN XAL.JOURNALENTRYLINEAEHEADERID IS NOT NULL THEN IFNULL(XAL.JOURNALENTRYLINEACCOUNTEDDR,0) END) END),2) AS DEBITO,
	ROUND((CASE WHEN XDL.JOURNALENTRYDISTRIBUTIONAEHEADERID IS NOT NULL THEN ROUND((IFNULL(XDL.JOURNALENTRYDISTRIBUTIONUNROUNDEDACCOUNTEDCR,0)),2)  ELSE (CASE WHEN XAL.JOURNALENTRYLINEAEHEADERID IS NOT NULL THEN IFNULL(XAL.JOURNALENTRYLINEACCOUNTEDCR,0) END) END),2) AS CREDITO,	
	ROUND((CASE WHEN XDL.JOURNALENTRYDISTRIBUTIONAEHEADERID IS NOT NULL THEN (ROUND((IFNULL(XDL.JOURNALENTRYDISTRIBUTIONUNROUNDEDACCOUNTEDDR,0)),2)  - ROUND((IFNULL(XDL.JOURNALENTRYDISTRIBUTIONUNROUNDEDACCOUNTEDCR,0)),2) ) ELSE (CASE WHEN XAL.JOURNALENTRYLINEAEHEADERID IS NOT NULL THEN (IFNULL(XAL.JOURNALENTRYLINEACCOUNTEDDR,0) - 	IFNULL(XAL.JOURNALENTRYLINEACCOUNTEDCR,0))END) END),2) AS PERIODO_ACT,
	XAL.JOURNALENTRYLINEACCOUNTINGDATE FH_CONTABLE,
	XAL.JOURNALENTRYLINELEDGERID LEDGERID,
FROM 
	 amrl-data-prd.RAW.FUSION_GL_IMPORT_REFERENCES GIR
	INNER JOIN  amrl-data-prd.RAW.FUSION_XLA_AE_LINES   XAL ON  SHA256(CAST(GIR.GLIMPORTREFERENCESGLSLLINKID AS STRING)) = SHA256(CAST(XAL.JOURNALENTRYLINEGLSLLINKID AS STRING)) AND GIR.GLIMPORTREFERENCESGLSLLINKTABLE = XAL.JOURNALENTRYLINEGLSLLINKTABLE	
	LEFT JOIN amrl-data-prd.RAW.FUSION_XLA_AE_HEADERS XAH   ON XAH.JOURNALENTRYHEADERAEHEADERID  =XAL.JOURNALENTRYLINEAEHEADERID		
	LEFT JOIN amrl-data-prd.RAW.FUSION_XLA_TRANSACTION_ENTITIES XTE ON XAH.JOURNALENTRYHEADERENTITYID =XTE.TRANSACTIONENTITYID	
	LEFT JOIN  amrl-data-prd.RAW.FUSION_XLA_DISTRIBUTION_LINKS   XDL  ON SHA256(CAST(XAL.JOURNALENTRYLINEAEHEADERID AS STRING))=SHA256(CAST(XDL.JOURNALENTRYDISTRIBUTIONAEHEADERID AS STRING)) AND XAL.JOURNALENTRYLINEAELINENUM= XDL.JOURNALENTRYDISTRIBUTIONAELINENUM;

END;