CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_CUENTAS_A_COBRAR()
OPTIONS(
  description="Información de cuentas a cobrar - Cobros")
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_CUENTAS_A_COBRAR PARTITION BY
   FH_COBRO   AS 
  
  
  
  SELECT ---Informacion Cobros de Cuentas a Cobrar
			222 APPLICATIONID,
			'RECEIPTS' AS ORIGEN,
			SHA256(CAST(ACRA.ARCASHRECEIPTCASHRECEIPTID AS STRING)) AS SK_IDORIGEN,
			ACRA.ARCASHRECEIPTCASHRECEIPTID 			AS BK_IDORIGEN,
			CASE WHEN STRPOS(ACRA.ARCASHRECEIPTATTRIBUTE1, '-') > 0 THEN SUBSTR(ACRA.ARCASHRECEIPTATTRIBUTE1, 1, STRPOS(ACRA.ARCASHRECEIPTATTRIBUTE1, '-') - 1) ELSE ACRA.ARCASHRECEIPTATTRIBUTE1 END								  AS NIT,
			ACRA.ARCASHRECEIPTATTRIBUTE6 					AS TERCERO,
			SHA256(CAST(ACRA.ARCASHRECEIPTPAYFROMCUSTOMER AS STRING)) AS SK_TERCERO,
			ACRA.ARCASHRECEIPTPAYFROMCUSTOMER 		AS BK_TERCERO,
			ACRA.ARCASHRECEIPTRECEIPTNUMBER 			AS DOCUMENTO,
			ACRA.ARCASHRECEIPTRECEIPTDATE 				AS FH_COBRO,
			ACRA.ARCASHRECEIPTCOMMENTS						AS DESCRIPCION
    FROM amrl-data-prd.RAW.FUSION_AR_CASH_RECEIPTS_ALL ACRA;
		END;