CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_OBT_PIVOT_FACT_OPORTUNIDAD()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla OBT_PIVOT_OPORTUNIDAD en el DataSet de COMSUPTION, La tabla contienes toda la informacion de la OBT_FACT_OPORTUNIDAD con la diferencia de que la cantidad de articulos asociados a una oportunidad se muestran en columnas y no en filas como en la OBT_FACT_OPORTUNIDAD. \nAutor: Maria Fernanda Franco\nUsos: Tracking Tools\nFecha de Creacion: 2025-01-15 10:36 AM \n\nModificaciones: \n20-05-2025: Se ajusta la consulta de la variable contador con el objetivo de identificar la oportunidad con mayor cantidad de artículos asociados(OP585373,585371, 585373 con 21 articulos)\nModificaciones:\n01-07-2025: Se incluyen las columnas IMPORTE_TOTAL_OP y ENCARGO_FIDUCIARIO")
BEGIN

DECLARE Consulta STRING;
DECLARE Contador INT64; 
DECLARE minimo INT64; 

--obtiene el numero maximo de columnas por pivotear
SET minimo = 1;
SET Contador = (
                  SELECT CANTIDAD_MAXIMA
                  FROM(
                        SELECT BK_NUMERO_OP, COUNT(BK_ARTICULO) AS CANTIDAD_MAXIMA
                        FROM `CONSUMPTION.OBT_FACT_OPORTUNIDAD`
                        WHERE ETAPA_DE_VENTA NOT IN ('1. Visita','0. Transición','2. Cotización de Reformas','3. Contrato de Reformas','4. Orden de Trabajo')
                        GROUP BY BK_NUMERO_OP
                  ) AS B 
                  ORDER BY CANTIDAD_MAXIMA DESC 
                  LIMIT 1
                );

-- Incluye los valores estaticos de la tabla OBT_FACT_OPORTUNIDAD
SET Consulta = "SELECT SK_OP,BK_COD_MACROPROYECTO,MACROPROYECTO,SK_COD_MACROCONSOLIDADOR,MACROCONSOLIDADOR,SK_COD_TRANSACCIONAL,TRANSACCIONAL,SALA_DE_VENTAS,SALA_DE_VENTAS_ALTERNATIVA,TIPO_DE_PROYECTO,ESTADO_PROYECTO,ESTADO_FINANCIERO_PROYECTO,CIUDAD,DIRECCION_PROYECTO,BANCO_CONSTRUCTOR,ENTIDAD_FIDUCIARIA,DIRECTOR_DE_VENTAS_VIVIENDAS_TRANSACCIONAL,DIRECTOR_DE_VENTAS_COMERCIOS_TRANSACCIONAL,FECHA_INICIO_VENTAS_TRANSACCIONAL,FECHA_PUNTO_DE_EQUILIBRIO,BK_NUMERO_OP,NOMBRE_OP,ETAPA_DE_VENTA,IMPORTE_TOTAL_OP,INMUEBLE_PRINCIPAL,BK_VENDEDOR,NOMBRE_VENDEDOR,OP_CREADA_POR,FECHA_DE_CREACION_OP,OP_ACTUALIZADA_POR,FECHA_ULTIMA_ACTUALIZACION_OP,ACEPTAR_VENTA,TIPO_VENTA,DESTINO,REFERIDO,OBSERVACIONES,PORCENTAJE_COMPRADORES,FECHA_DE_SEPARACION,FECHA_COMPROMISO_RADICACION_CREDITO,FECHA_COMPROMISO_RADICACION_SUBSIDIO,INMUEBLE_OPCIONADO,ENTIDAD_CREDITO,MONTO_CREDITO,ENTIDAD_CREDITO_TER_1,MONTO_CREDITO_TER_1,ENTIDAD_CREDITO_TER_2,MONTO_CREDITO_TER_2,ENTIDAD_SUBSIDIO_1,MONTO_SUBSIDIO_1,ENTIDAD_SUBSIDIO_2, MONTO_SUBSIDIO_2,PUNTO_DE_EQUILIBRIO,BLOQUEO,NUMERO_DE_ESCRITURA,FECHA_DE_ESCRITURA,NOTARIA,CIRCULO_NOTARIAL,DESISTIDO,FECHA_DESISTIDO,FECHA_RADICADO_DOCUMENTOS_DESISTIMIENTO,CAUSA_DESISTIMIENTO,TIPO_DESISTIMIENTO,OBSERVACION_DESISTIMIENTO,BK_PERSONA,COMPRADOR1,IDENTIFICACION_COMPRADOR1,FECHA_DE_NACIMIENTO_COMPRADOR1,PAIS_COMPRADOR1,CIUDAD_COMPRADOR1,DIRECCION_COMPRADOR1,EMAIL_COMPRADOR1,TELEFONO_COMPRADOR1,GENERO_COMPRADOR1,ESTADO_CIVIL_COMPRADOR1,OCUPACION_COMPRADOR1,BK_COMPRADOR2,COMPRADOR2,IDENTIFICACION_COMPRADOR2,FECHA_DE_NACIMIENTO_COMPRADOR2,PAIS_COMPRADOR2,CIUDAD_COMPRADOR2,DIRECCION_COMPRADOR2,EMAIL_COMPRADOR2,TELEFONO_COMPRADOR2,GENERO_COMPRADOR2,ESTADO_CIVIL_COMPRADOR2,OCUPACION_COMPRADOR2,BK_OP,BSTR,RVDF,ASUB,VSUB,ASMY,VSMY,ARSC,ACAV,VCAV,AOCR,ACDS,VCDS,FPRC,EPP5,SAVA,LLAV,RNOV,ANOV,RLEG,LNEG,ALEG,VLEG,OESV,PSCA,SCCM,LLCM,EACC,ACCC,FESC,LLES,ECNT,LCRN,EEFA,LLEA,SPPT,PPPT,EFLB,LLFL,EEFB,LLEB,EACN,LLCN,SCHE,REPG,ECEG,IREG,SRE1,CRR1,SRE2,CRR2,SDER,CIVA,EIRE,EACT,ISPH,SHAB,LHAB,AS80,AS20,ADSU,ADSC,FEGB,CLCR,RASB,RADS,ADMY,ECSV,SUBR,NCAV,DSUB,ODSE,APRE,FENC,EGAE,RCAV,EFCO,AMFN,LENT,OCNO,RMFN,EGA2,DESE,ETGB,EPRO,ROCR,LLCG,LLPT,LMHF,LLST,EPRV,EPP1,EPP2,EPP3,EPP4,LLAP,PEQU,SLCC,SCAF,EPRA,ECFL,LLGA,SMHF,SNRF,ANRF,DSMY,EFSV,PSLB,RSMY,EEB2,ELNR,VCOE,DNRF,ECBN,EDNR,LLCA,LCNB,LLPA,EIPR,RACH,VOCN,EVBA,FPEF,FAPA,SPVP,VBOE,FPDC,ENCH,EISC,RPSU,LTCN,SRPF,CIEL,DS20,DS80,ECAP,EENF,EENS,EPEF,FPVS,LPMJ,DGSV,EAMS,ICGR,LACF,LLEF,LRCG,FPOC,EEFF,LLVB,LFCN,OCNP,RGPB,EOEN,SRPH,DEBC,DPCN,EPPE,LPPE,SACF,FOCN,FANC,FPCB,LCVV,RSUB,EEPM,LCEC,LPMA,TPVM,VTPM,EDAP,FAPF,SCEG,FPPE,LDMF,OKNC,RVCF,AACH,DOEV,LPMF,PEHB,DVCF,EPMA,FCAP,FOMI,RVCV,VACH,VOCR,EVPE,APCF,EBPG,SVCN,FTPM,LFPE,CICV,VPCF,SVMI,EPCF,EMCF,FAMI,FRAM,LTPM,VRAM,EVDV,EFPE,EFCF,LPCF,LOMI,LRAM,RAVM,EPOC,LMCF,EOCF,LPOC,LOCF,FRES,RDES,LFH2,OMCY,SDES,LMCY,RZMT,EEAR,RMTP,PSUB,EFH2,RAC2,REHP,VBCC,LPSB,LLMN,NIFP,CIFL,EPMJ,SVMS,AFEC,ASMP,DRAO,EFPA,FECS,LEOC,LFAP,RAO2,LFMS,ARTC,DRAC,DADS,EFCS,EEFO,MSEF,FNAE,NDVC,LTNP,CNEF,EVCA,ECNF,ADS2,DSVA,LTMS,CAVF,LPET,EPEV,EEPF,CAEF,EVB2,LFNP,FCNP,LFPA,FECN,VONP,FEPE,AFEN, ASCC, DVSB,FECHA_PROYECTADA_RPH,FECHA_REAL_RPH,MAX(CASE WHEN PivotArticulo = 1 THEN FECHA_PROYECTADA_CTO END) AS FECHA_PROYECTADA_CTO, MAX(CASE WHEN PivotArticulo = 1 THEN FECHA_REAL_CTO END) AS FECHA_REAL_CTO,MAX(CASE WHEN PivotArticulo = 1 THEN FECHA_PROYECTADA_ESCRITURACION END) AS FECHA_PROYECTADA_ESCRITURACION,MAX(CASE WHEN PivotArticulo = 1 THEN FECHA_REAL_POLIZA_DECENAL END) AS FECHA_PROYECTADA_POLIZA_DECENAL,MAX(CASE WHEN PivotArticulo = 1 THEN FECHA_REAL_POLIZA_DECENAL END) AS FECHA_REAL_POLIZA_DECENAL,MAX(CASE WHEN PivotArticulo = 1 THEN MATRICULA_INMOBILIARIA END) AS MATRICULA_INMOBILIARIA,MAX(CASE WHEN PivotArticulo = 1 THEN ENCARGO_FIDUCIARIO END) AS ENCARGO_FIDUCIARIO,";

--Itera en la variable Contador para las columnas que requieren el pivot 
WHILE minimo <= Contador DO
  SET Consulta = CONCAT(Consulta,
                        " MAX(CASE WHEN PivotArticulo = ", minimo ," THEN BK_ARTICULO END) AS BK_ARTICULO_", minimo, 
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN NOMBRE_ARTICULO END) AS NOMBRE_ARTICULO", minimo,
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN REFERENCIA END) AS REFERENCIA_ARTICULO", minimo,
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN ESTADO_DEL_ARTICULO END) AS ESTADO_DEL_ARTICULO", minimo,
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN CLASE_DE_ARTICULO END) AS CLASE_DE_ARTICULO", minimo,
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN AREA_CONSTRUIDA END) AS AREA_CONSTRUIDA_ARTICULO", minimo,                        
                        ",\n MAX(CASE WHEN PivotArticulo = ", minimo ," THEN PRECIO_UNITARIO END) AS PRECIO_UNITARIO_ARTICULO", minimo , ",\n"
                        ) ;

  SET minimo = minimo + 1;
END WHILE;

SET Consulta = substr(Consulta,1, (length(Consulta)-2)); --quita la ultima coma (,) antes del FROM.
--Incluye los datos de FROM y GROUP BY 
SET Consulta = CONCAT(Consulta, "\n FROM ( SELECT *, ROW_NUMBER() OVER (PARTITION BY SK_OP ORDER BY PRECIO_UNITARIO DESC)  AS PivotArticulo FROM `CONSUMPTION.OBT_FACT_OPORTUNIDAD` ) AS A WHERE ETAPA_DE_VENTA NOT IN ('1. Visita','0. Transición','2. Cotización de Reformas','3. Contrato de Reformas','4. Orden de Trabajo') GROUP BY SK_OP, BK_COD_MACROPROYECTO, MACROPROYECTO, SK_COD_MACROCONSOLIDADOR, MACROCONSOLIDADOR, SK_COD_TRANSACCIONAL, TRANSACCIONAL, SALA_DE_VENTAS, SALA_DE_VENTAS_ALTERNATIVA, TIPO_DE_PROYECTO, ESTADO_PROYECTO,ESTADO_FINANCIERO_PROYECTO, CIUDAD, DIRECCION_PROYECTO, BANCO_CONSTRUCTOR, ENTIDAD_FIDUCIARIA, DIRECTOR_DE_VENTAS_VIVIENDAS_TRANSACCIONAL, DIRECTOR_DE_VENTAS_COMERCIOS_TRANSACCIONAL, FECHA_INICIO_VENTAS_TRANSACCIONAL, FECHA_PUNTO_DE_EQUILIBRIO, BK_NUMERO_OP, NOMBRE_OP, ETAPA_DE_VENTA,IMPORTE_TOTAL_OP,INMUEBLE_PRINCIPAL, BK_VENDEDOR, NOMBRE_VENDEDOR, OP_CREADA_POR, FECHA_DE_CREACION_OP, OP_ACTUALIZADA_POR, FECHA_ULTIMA_ACTUALIZACION_OP, ACEPTAR_VENTA, TIPO_VENTA, DESTINO, REFERIDO, OBSERVACIONES, PORCENTAJE_COMPRADORES, FECHA_DE_SEPARACION, FECHA_COMPROMISO_RADICACION_CREDITO, FECHA_COMPROMISO_RADICACION_SUBSIDIO, INMUEBLE_OPCIONADO, ENTIDAD_CREDITO, MONTO_CREDITO, ENTIDAD_CREDITO_TER_1, MONTO_CREDITO_TER_1,ENTIDAD_CREDITO_TER_2,MONTO_CREDITO_TER_2, ENTIDAD_SUBSIDIO_1, MONTO_SUBSIDIO_1, ENTIDAD_SUBSIDIO_2, MONTO_SUBSIDIO_2,PUNTO_DE_EQUILIBRIO, BLOQUEO, NUMERO_DE_ESCRITURA, FECHA_DE_ESCRITURA, NOTARIA, CIRCULO_NOTARIAL, DESISTIDO, FECHA_DESISTIDO, FECHA_RADICADO_DOCUMENTOS_DESISTIMIENTO, CAUSA_DESISTIMIENTO, TIPO_DESISTIMIENTO, OBSERVACION_DESISTIMIENTO, BK_PERSONA, COMPRADOR1, IDENTIFICACION_COMPRADOR1, FECHA_DE_NACIMIENTO_COMPRADOR1, PAIS_COMPRADOR1, CIUDAD_COMPRADOR1, DIRECCION_COMPRADOR1, EMAIL_COMPRADOR1, TELEFONO_COMPRADOR1, GENERO_COMPRADOR1, ESTADO_CIVIL_COMPRADOR1, OCUPACION_COMPRADOR1, BK_COMPRADOR2, COMPRADOR2, IDENTIFICACION_COMPRADOR2, FECHA_DE_NACIMIENTO_COMPRADOR2, PAIS_COMPRADOR2, CIUDAD_COMPRADOR2, DIRECCION_COMPRADOR2, EMAIL_COMPRADOR2, TELEFONO_COMPRADOR2, GENERO_COMPRADOR2, ESTADO_CIVIL_COMPRADOR2, OCUPACION_COMPRADOR2, BK_OP, BSTR, RVDF, ASUB, VSUB, ASMY, VSMY, ARSC, ACAV, VCAV, AOCR, ACDS, VCDS, FPRC, EPP5, SAVA, LLAV, RNOV, ANOV, RLEG, LNEG, ALEG, VLEG, OESV, PSCA, SCCM, LLCM, EACC, ACCC, FESC, LLES, ECNT, LCRN, EEFA, LLEA, SPPT, PPPT, EFLB, LLFL, EEFB, LLEB, EACN, LLCN, SCHE, REPG, ECEG, IREG, SRE1, CRR1, SRE2, CRR2, SDER, CIVA, EIRE, EACT, ISPH, SHAB, LHAB, AS80, AS20, ADSU, ADSC, FEGB, CLCR, RASB, RADS, ADMY, ECSV, SUBR, NCAV, DSUB, ODSE, APRE, FENC, EGAE, RCAV, EFCO, AMFN, LENT, OCNO, RMFN, EGA2, DESE, ETGB, EPRO, ROCR, LLCG, LLPT, LMHF, LLST, EPRV, EPP1, EPP2, EPP3, EPP4, LLAP, PEQU, SLCC, SCAF, EPRA, ECFL, LLGA, SMHF, SNRF, ANRF, DSMY, EFSV, PSLB, RSMY, EEB2, ELNR, VCOE, DNRF, ECBN, EDNR, LLCA, LCNB, LLPA, EIPR, RACH, VOCN, EVBA, FPEF, FAPA, SPVP, VBOE, FPDC, ENCH, EISC, RPSU, LTCN, SRPF, CIEL, DS20, DS80, ECAP, EENF, EENS, EPEF, FPVS, LPMJ, DGSV, EAMS, ICGR, LACF, LLEF, LRCG, FPOC, EEFF, LLVB, LFCN, OCNP, RGPB, EOEN, SRPH, DEBC, DPCN, EPPE, LPPE, SACF, FOCN, FANC, FPCB, LCVV, RSUB, EEPM, LCEC, LPMA, TPVM, VTPM, EDAP, FAPF, SCEG, FPPE, LDMF, OKNC, RVCF, AACH, DOEV, LPMF, PEHB, DVCF, EPMA, FCAP, FOMI, RVCV, VACH, VOCR, EVPE, APCF, EBPG, SVCN, FTPM, LFPE, CICV, VPCF, SVMI, EPCF, EMCF, FAMI, FRAM, LTPM, VRAM, EVDV, EFPE, EFCF, LPCF, LOMI, LRAM, RAVM, EPOC, LMCF, EOCF, LPOC, LOCF, FRES, RDES, LFH2, OMCY, SDES, LMCY, RZMT, EEAR, RMTP, PSUB, EFH2, RAC2, REHP, VBCC, LPSB, LLMN, NIFP, CIFL, EPMJ, SVMS, AFEC, ASMP, DRAO, EFPA, FECS, LEOC, LFAP, RAO2, LFMS, ARTC, DRAC, DADS, EFCS, EEFO, MSEF, FNAE, NDVC, LTNP, CNEF, EVCA, ECNF, ADS2, DSVA, LTMS, CAVF, LPET, EPEV, EEPF, CAEF, EVB2, LFNP, FCNP, LFPA, FECN, VONP, FEPE,AFEN, ASCC, DVSB, FECHA_PROYECTADA_RPH,FECHA_REAL_RPH");

--Imprime la consulta construida
SELECT Consulta;

--Ejecuta la consulta y la inserta en la tabla `CONSUMPTION.PIVOT_OBT_FACT_OPORTUNIDAD` ' ||
EXECUTE IMMEDIATE 
 'CREATE OR REPLACE TABLE `CONSUMPTION.PIVOT_OBT_FACT_OPORTUNIDAD` ' ||
 'PARTITION BY FECHA_DE_SEPARACION ' ||
 'CLUSTER BY SALA_DE_VENTAS, SK_COD_TRANSACCIONAL ' ||
 'AS ' || Consulta;


END;