CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_OBT_FACT_GESTION_PROYECTOS()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla OBT_FACT_GESTION_PROYECTOS en el DataSet de CONSUMPTION, La tabla consolida los atributos revelantes de cada subetapa. Contiene datos como el codigo macroconsolidador y codigo macroproyecto.\nAutor: Anderson Murte\nUsos: Uso transversal para las areas todas las areas de la compañia\nModificaciones:\n08-09-2025: Se incluyen las columnas VALOR_DE_SEPARACION_PACTADO_PROYECTO y VALOR_DE_CONFIRMACION_PACTADO_PROYECTO")
BEGIN
    CREATE OR REPLACE TABLE `amrl-data-prd.CONSUMPTION.OBT_FACT_GESTION_PROYECTOS` 
    PARTITION BY DATE(FECHA_CREACION_TRANSACCIONAL) 
    CLUSTER BY MACROPROYECTO, MACROCONSOLIDADOR, TRANSACCIONAL, TIPO_DE_PROYECTO AS   

    SELECT  DSE.BK_COD_MACROPROYECTO
          ,dmp.MACROPROYECTO
          ,dmc.SK_COD_MACROCONSOLIDADOR
          ,dmc.MACROCONSOLIDADOR
          ,DSE.SK_COD_TRANSACCIONAL
          ,DSE.TRANSACCIONAL
          ,DSE.TIPO_DE_PROYECTO                    AS TIPO_DE_PROYECTO
          ,DSE.ESTADO_PROYECTO                     AS ESTADO_PROYECTO
          ,DSE.ESTADO_FINANCIERO_PROYECTO          AS ESTADO_FINANCIERO_PROYECTO
          ,DSE.CIUDAD
          ,DSE.DIRECCION_PROYECTO                  AS DIRECCION_PROYECTO
          ,DSE.ESTRATO
          ,DSE.SALA_DE_VENTAS                      AS SALA_DE_VENTAS
          ,DSE.SALA_DE_VENTAS_ALTERNATIVA
          ,DSE.ENTIDAD_FIDUCIARIA                  AS ENTIDAD_FIDUCIARIA  
          ,DSE.BANCO_CONSTRUCTOR                   AS BANCO_CONSTRUCTOR
          ,DSE.BANCO_RECAUDADOR                    AS BANCO_RECAUDADOR
          ,DSE.CUENTA_RECAUDADORA                  AS CUENTA_RECAUDADORA
          ,dmp.TOTAL_VIVIENDAS_MACROPROYECTO
          ,dmp.TOTAL_COMERCIOS_MACROPROYECTO
          ,DSE.TOTAL_VIVIENDAS_TRANSACCIONAL       AS TOTAL_VIVIENDAS_SUBETAPA
          ,DSE.TOTAL_COMERCIOS_TRANSACCIONAL       AS TOTAL_COMERCIOS_SUBETAPA
          ,DSE.ENCARGO_FIDUCIARIO_PROYECTO
          ,DSE.FECHA_MAXIMA_CUOTA_INICIAL     
          ,DSE.VALOR_SEPARACION                    AS VALOR_DE_SEPARACION_PACTADO_PROYECTO
          ,DSE.VALOR_CONFIRMACION                  AS VALOR_DE_CONFIRMACION_PACTADO_PROYECTO
          ,DSE.DIRECTOR_DE_VENTAS_COMERCIOS_TRANSACCIONAL                  AS DIRECTOR_DE_VENTAS_COMERCIOS_SUBETAPA
          ,DSE.DIRECTOR_DE_VENTAS_VIVIENDAS_TRANSACCIONAL                  AS DIRECTOR_DE_VENTAS_VIVIENDAS_SUBETAPA
          ,DSE.RITMO_VENTAS_TRANSACCIONAL
          ,DSE.COORDINADOR_ENCARGADO               AS COORDINADOR_ENCARGADO
          ,DSE.FECHA_CREACION_TRANSACCIONAL        AS FECHA_CREACION_TRANSACCIONAL
          ,DSE.FECHA_PUNTO_DE_EQUILIBRIO           AS FECHA_PUNTO_DE_EQUILIBRIO
          ,DSE.FECHA_PROYECTADA_RPH
          ,DSE.FECHA_REAL_RPH
          ,DSE.NOMBRE_PROYECTO_HV --Dato similar al macroptoyecto pendiente confirmacion con Jhon Quiroz
          ,DSE.FECHA_ULTIMA_ACTUALIZACION_ORC      AS FECHA_ULTIMA_ACTUALIZACION_ORC
          ,DSE.FECHA_ACTUALIZACION_BQ
          ,DSE.FECHA_CARGUE_BQ       
    FROM `PRESENTATION.DIM_SUB_ETAPA` DSE
    LEFT JOIN `PRESENTATION.DIM_MACROCONSOLIDADOR` dmc ON dse.BK_COD_MACROCONSOLIDADOR = dmc.SK_COD_MACROCONSOLIDADOR 
    LEFT JOIN `PRESENTATION.DIM_MACROPROYECTO` dmp ON dse.BK_COD_MACROPROYECTO = dmp.SK_COD_MACROPROYECTO;

END;