CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FUSION_RA_CUST_TRX_TYPES_ALL_DELETED()
BEGIN
  -- Step 1: Crear una tabla temporal con los RACUSTTRXTYPECUSTTRXTYPESEQID de RAW.RA_CUST_TRX_TYPES_ALL que no están en STAGING.RA_CUST_TRX_TYPES_ALL_PK
  CREATE TEMP TABLE ids_a_actualizar5 AS
  SELECT
    trx.RACUSTTRXTYPECUSTTRXTYPESEQID
  FROM
    `amrl-data-prd.RAW.FUSION_RA_CUST_TRX_TYPES_ALL` AS trx
  LEFT JOIN
    `amrl-data-prd.STAGING.FUSION_RA_CUST_TRX_TYPES_ALL_PK` AS trx_pk
  ON
    trx.RACUSTTRXTYPECUSTTRXTYPESEQID = trx_pk.RACUSTTRXTYPECUSTTRXTYPESEQID
  WHERE
    trx_pk.RACUSTTRXTYPECUSTTRXTYPESEQID IS NULL;

  -- Step 2: Actualizar la columna DELETED en la tabla RAW.RA_CUST_TRX_TYPES_ALL para los registros que están en la tabla temporal
  UPDATE
    `amrl-data-prd.RAW.FUSION_RA_CUST_TRX_TYPES_ALL`
  SET
    DELETED = '1'
  WHERE
    RACUSTTRXTYPECUSTTRXTYPESEQID IN (SELECT RACUSTTRXTYPECUSTTRXTYPESEQID FROM ids_a_actualizar5);

  -- Step 3: Limpiar la tabla temporal
  DROP TABLE ids_a_actualizar5;
END;