CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_DIM_COBRO()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla DIM_COBRO consolidando todos los atributos de los cobros para cada concepto en el plan de pagos\nAutor: Maria Fernanda Franco\nUsos: Dashboard RecaudoTotal\nModificaciones: \n2025-03-10: Se modifica la columna IMPORTE INTRODUCIDO, antes ACRA.ARCASHRECEIPTAMOUNT  ahora ARA.ARRECEIVABLEAPPLICATIONAMOUNTAPPLIED\n2025-08-13: Se incluye la columna FECHA_DE_APLICACION y se modifica el origen de la FECHA_CONTABLE antes ACRA.ARCASHRECEIPTCREATIONDATE ahora APS.ARPAYMENTSCHEDULEGLDATE ")
BEGIN

CREATE TEMP TABLE TEMP_COBRO AS (
        SELECT ROW_NUMBER() OVER (ORDER BY ACRA.ARCASHRECEIPTRECEIPTDATE) AS ID_DIM_COBRO
               ,RCTA.RACUSTOMERTRXCUSTOMERTRXID              AS SK_COBRO
               ,ACRA.ARCASHRECEIPTATTRIBUTE4                 AS NUMERO_DE_COBRO
               ,ACRA.ARCASHRECEIPTDOCSEQUENCEVALUE           AS RECIBO
               ,ACRA.ARCASHRECEIPTSTATUS                     AS ESTADO_DEL_COBRO
               ,ARA.ARRECEIVABLEAPPLICATIONAMOUNTAPPLIED     AS IMPORTE_APLICADO --PUEDE SER TAMBIEN ARRECEIVABLEAPPLICATIONACCTDAMOUNTAPPLIEDFROM, ARRECEIVABLEAPPLICATIONACCTDAMOUNTAPPLIEDTO   
               ,ARM.ARRECEIPTCLASSNAME                       AS METODO_DE_COBRO
               ,ACRA.ARCASHRECEIPTRECEIPTNUMBER              AS REFERENCIA_DE_APLICACION 
               ,RCTA.RACUSTOMERTRXDOCSEQUENCEVALUE           AS NUMERO_DE_DOCUMENTO
               ,APS.ARPAYMENTSCHEDULEPAYMENTSCHEDULECLASS1   AS TIPO_DE_COBRO
               ,ARA.ARRECEIVABLEAPPLICATIONDAYSLATE          AS DIAS_DE_MORA 	
               ,ACRA.ARCASHRECEIPTRECEIPTDATE                AS FECHA_DE_COBRO           
               ,APS.ARPAYMENTSCHEDULEGLDATE                  AS FECHA_CONTABLE
               ,APS.ARPAYMENTSCHEDULEACTUALDATECLOSED        AS FECHA_DE_APLICACION
               ,HZCA.ACCOUNTNUMBER                           AS NUMERO_DE_CUENTA_DEL_CLIENTE
               ,HCSUA.LOCATION                               AS NUMERO_DE_SITIO		 
               ,ACRA.ARCASHRECEIPTCUSTOMERSITEUSEID          AS BK_SITIO_CLIENTE  
               ,HZCA.PARTYID                                 AS BK_PERSONA	
               ,CURRENT_DATETIME("America/Bogota")           AS FECHA_ACTUALIZACION_BQ
               ,CURRENT_DATETIME("America/Bogota")           AS FECHA_CARGUE_BQ
        FROM `RAW.FUSION_AR_CASH_RECEIPTS_ALL` ACRA
        LEFT JOIN `RAW.FUSION_AR_RECEIPT_METHODS` ARM             ON ACRA.ARCASHRECEIPTRECEIPTMETHODID = ARM.ARRECEIPTMETHODRECEIPTMETHODID
        LEFT JOIN `RAW.FUSION_AR_RECEIVABLE_APPLICATIONS_ALL` ARA ON ARA.ARRECEIVABLEAPPLICATIONCASHRECEIPTID = ACRA.ARCASHRECEIPTCASHRECEIPTID
        LEFT JOIN `RAW.FUSION_RA_CUSTOMER_TRX_ALL` RCTA           ON ARA.ARRECEIVABLEAPPLICATIONAPPLIEDCUSTOMERTRXID = RCTA.RACUSTOMERTRXCUSTOMERTRXID
        LEFT JOIN `RAW.FUSION_AR_PAYMENT_SCHEDULES_ALL` APS       ON ARA.ARRECEIVABLEAPPLICATIONPAYMENTSCHEDULEID = APS.ARPAYMENTSCHEDULEPAYMENTSCHEDULEID
        LEFT JOIN `RAW.FUSION_HZ_CUST_SITE_USES_ALL` HCSUA        ON ACRA.ARCASHRECEIPTCUSTOMERSITEUSEID = HCSUA.SITEUSEID
        LEFT JOIN `RAW.FUSION_HZ_CUST_ACCT_SITES_ALL` HZCASA      ON HCSUA.CUSTACCTSITEID = HZCASA.CUSTOMERACCOUNTSITECUSTACCTSITEID
        LEFT JOIN `RAW.FUSION_HZ_CUST_ACCOUNTS` HZCA              ON HZCASA.CUSTACCOUNTID = HZCA.CUSTACCOUNTID
        WHERE RCTA.RACUSTOMERTRXCUSTOMERTRXID IS NOT NULL
            --AND ACRA.ARCASHRECEIPTRECEIPTNUMBER = 'AVS.896486600' 
    );
  

--CREATE OR REPLACE TABLE PRESENTATION.DIM_COBRO AS 
--SELECT * FROM TEMP_COBRO 

    MERGE   PRESENTATION.DIM_COBRO AS T
    USING   (SELECT * FROM TEMP_COBRO) AS S
    ON      (T.ID_DIM_COBRO = S.ID_DIM_COBRO)
    WHEN MATCHED THEN
    UPDATE SET  T.SK_COBRO                       =   S.SK_COBRO,
                T.NUMERO_DE_COBRO                =   S.NUMERO_DE_COBRO,
                T.RECIBO                         =   S.RECIBO,
                T.ESTADO_DEL_COBRO               =   S.ESTADO_DEL_COBRO,  
                T.IMPORTE_APLICADO               =   S.IMPORTE_APLICADO,                
                T.METODO_DE_COBRO                =   S.METODO_DE_COBRO,
                T.REFERENCIA_DE_APLICACION       =   S.REFERENCIA_DE_APLICACION,
                T.NUMERO_DE_DOCUMENTO            =   S.NUMERO_DE_DOCUMENTO,
                T.TIPO_DE_COBRO                  =   S.TIPO_DE_COBRO,
                T.DIAS_DE_MORA                   =   S.DIAS_DE_MORA,
                T.FECHA_DE_COBRO                 =   S.FECHA_DE_COBRO,
                T.FECHA_CONTABLE                 =   S.FECHA_CONTABLE, 
                T.NUMERO_DE_CUENTA_DEL_CLIENTE   =   S.NUMERO_DE_CUENTA_DEL_CLIENTE,
                T.NUMERO_DE_SITIO                =   S.NUMERO_DE_SITIO,
                T.BK_SITIO_CLIENTE               =   S.BK_SITIO_CLIENTE,                
                T.BK_PERSONA                     =   S.BK_PERSONA,       
                T.FECHA_ACTUALIZACION_BQ         =   CURRENT_DATETIME("America/Bogota")
    WHEN NOT MATCHED THEN
    INSERT  (   ID_DIM_COBRO,
                SK_COBRO,
                NUMERO_DE_COBRO,
                RECIBO,
                ESTADO_DEL_COBRO,                
                IMPORTE_APLICADO,
                METODO_DE_COBRO,
                REFERENCIA_DE_APLICACION,
                NUMERO_DE_DOCUMENTO,
                TIPO_DE_COBRO,
                DIAS_DE_MORA, 
                FECHA_DE_COBRO, 
                FECHA_CONTABLE, 
                NUMERO_DE_CUENTA_DEL_CLIENTE, 
                NUMERO_DE_SITIO,
                BK_SITIO_CLIENTE, 
                BK_PERSONA,
                FECHA_ACTUALIZACION_BQ,
                FECHA_CARGUE_BQ
                
            )
    VALUES (    ID_DIM_COBRO,
                S.SK_COBRO,
                S.NUMERO_DE_COBRO,
                S.RECIBO,
                S.ESTADO_DEL_COBRO,                
                S.IMPORTE_APLICADO,
                S.METODO_DE_COBRO,
                S.REFERENCIA_DE_APLICACION,
                S.NUMERO_DE_DOCUMENTO,
                S.TIPO_DE_COBRO,
                S.DIAS_DE_MORA, 
                S.FECHA_DE_COBRO, 
                S.FECHA_CONTABLE, 
                S.NUMERO_DE_CUENTA_DEL_CLIENTE, 
                S.NUMERO_DE_SITIO,
                S.BK_SITIO_CLIENTE, 
                S.BK_PERSONA, 
                CURRENT_DATETIME("America/Bogota"),
                CURRENT_DATETIME("America/Bogota")
            );
END;