CREATE PROCEDURE `amrl-data-prd`.MONITORING.SP_TBL_MONITOREO_MOO_RVN()
BEGIN


--CREATE OR REPLACE TABLE `amrl-data-prd.MONITORING.TBL_MONITOREO_MOO_RVN` AS 

MERGE `amrl-data-prd.MONITORING.TBL_MONITOREO_MOO_RVN`  AS TMMR
USING 
(
SELECT
  MAX(CASE WHEN ORIGEN = 'MOO_REVN_STAGING' THEN CANTIDAD END) AS MOO_REVN_STAGING ,
  MAX(CASE WHEN ORIGEN = 'MOO_REVN_RAW' THEN CANTIDAD END) AS MOO_REVN_RAW,
  (MAX(CASE WHEN ORIGEN = 'MOO_REVN_STAGING' THEN CANTIDAD END) - MAX(CASE WHEN ORIGEN = 'MOO_REVN_RAW' THEN CANTIDAD END)) AS DIFERENCIA,
  CASE
    WHEN (MAX(CASE WHEN ORIGEN = 'MOO_REVN_STAGING' THEN CANTIDAD END) - MAX(CASE WHEN ORIGEN = 'MOO_REVN_RAW' THEN CANTIDAD END)) <> 0
    THEN 'CON DIFERENCIA'
    ELSE 'SIN DIFERENCIA'
  END AS ESTADO,
  CURRENT_DATE() AS FECHA
FROM (
        SELECT 'MOO_REVN_STAGING' AS ORIGEN,
               COUNT(*) AS CANTIDAD
               
        FROM `amrl-data-prd.RAW.FUSION_MOO_REVN` AS revn
        LEFT JOIN `amrl-data-prd.STAGING.FUSION_MOO_REVN_PK` AS revn_pk
          ON revn.REVENUEREVNID = revn_pk.REVENUEREVNID
        WHERE revn_pk.REVENUEREVNID IS NULL

        UNION ALL

        SELECT 
          'MOO_REVN_RAW' AS ORIGEN,
          COUNT(*) AS CANTIDAD
        FROM `RAW.FUSION_MOO_REVN`
        WHERE DELETED IS NOT NULL
     ) 
) AS T1

ON TMMR.FECHA = T1.FECHA


WHEN MATCHED THEN
  UPDATE SET  TMMR.MOO_REVN_STAGING = T1.MOO_REVN_STAGING,
              TMMR.MOO_REVN_RAW = T1.MOO_REVN_RAW,
              TMMR.DIFERENCIA = T1.DIFERENCIA,
              TMMR.ESTADO = T1.ESTADO

WHEN NOT MATCHED THEN
  INSERT (MOO_REVN_STAGING, MOO_REVN_RAW, DIFERENCIA, ESTADO, FECHA)
  VALUES (T1.MOO_REVN_STAGING, T1.MOO_REVN_RAW, T1.DIFERENCIA, T1.ESTADO, T1.FECHA);

END;