CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_BALANCE_GRAL()
OPTIONS(
  description="Información del balance general, información del modulo de contabilidad general")
BEGIN
		CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_BALANCE_GRAL PARTITION BY FH_CONTABLE CLUSTER BY ORIGEN AS 
	/**************************** operacion construye la tabla de hechos del balande general del modulo de contabilidad general en la opcion de consultar saldos ***************************/
	SELECT  
			SHA256(CAST(GJL.JEHEADERID AS STRING)) 		 AS SK_JEHEADERID,
			GJL.JEHEADERID 						 AS BK_JEHEADERID,
			GL.LEDGERNAME 						 AS LIBRO,
			IFNULL(ROUND(CAST(gjl.GLJELINESACCOUNTEDDR AS NUMERIC), 2),0) 	AS DEBITO,
			IFNULL(ROUND(CAST(gjl.GLJELINESACCOUNTEDCR AS NUMERIC), 2),0)		AS  CREDITO,
			SHA256(CAST(GJL.GLJELINESCODECOMBINATIONID AS STRING)) 					AS SK_COMBINATION_ID,
			GJL.JELINENUM 						 AS LINENUM,
			GJL.GLJELINESPERIODNAME 	 AS PERIODO,
			REGEXP_EXTRACT(COALESCE( GJL.GLJELINESATTRIBUTE1,GJL.GLJELINESATTRIBUTE12), r'^[^-]+') NIT,
			GJL.GLJELINESATTRIBUTE13 											AS TERCERO,
			GJL.GLJELINESCURRENCYCODE									  	AS MONEDA,
			GJST.JRNLSRCTRANSLATIONUSERJESOURCENAME 			AS ORIGEN,
			GJCT.JRNLCATTRANSLATIONUSERJECATEGORYNAME 		AS CATEGORIA,
			GJL.GLJELINESEFFECTIVEDATE 										AS FH_CONTABLE,
			GJH.GLJEHEADERSCREATEDBY,
			GJH.GLJEHEADERSCREATIONDATE,
			GLJEHEADERSEXTERNALREFERENCE,
			GLJEHEADERSDESCRIPTION,
			GLJEHEADERSNAME,
			GLJEHEADERSPERIODNAME,
			GJH.GLJEHEADERSPOSTINGACCTSEQVALUE 						AS DOCUMENTO_CON,
			GJH.GLJEHEADERSNAME 													AS CONCEPTO,
			REPLACE(GJL.GLJELINESDESCRIPTION,CHR(10),' ') AS	DESCRIPCION

		FROM `amrl-data-prd.RAW.FUSION_GL_JE_HEADERS` GJH 
				INNER JOIN  `amrl-data-prd.RAW.FUSION_GL_JE_LINES` GJL ON  GJL.JEHEADERID =GJH.JEHEADERID
				INNER JOIN  `amrl-data-prd.RAW.FUSION_GL_LEDGERS` GL ON GL.LEDGERLEDGERID=GJH.GLJEHEADERSLEDGERID
				INNER JOIN  `amrl-data-prd.RAW.FUSION_GL_JE_SOURCES_TL` GJST ON GJST.JRNLSRCTRANSLATIONJESOURCENAME=GJH.GLJEHEADERSJESOURCE
				INNER JOIN  `amrl-data-prd.RAW.FUSION_GL_JE_CATEGORIES_TL` GJCT ON GJCT.JRNLCATTRANSLATIONJECATEGORYNAME=GJH.GLJEHEADERSJECATEGORY  

				INNER JOIN  `amrl-data-prd.PRESENTATION.DIM_PERIODOS` PER ON PER.BK_PERIODO=	GJL.GLJELINESPERIODNAME 
			

	WHERE 
		GJST.JRNLSRCTRANSLATIONLANGUAGE='E'
		AND GJCT.JRNLCATTRANSLATIONLANGUAGE='E'
		AND GJH.GLJEHEADERSACTUALFLAG ='A'
		AND GJH.GLJEHEADERSSTATUS='P'
		AND GJL.GLJELINESSTATUS='P'
		AND (	IFNULL(ROUND(CAST(gjl.GLJELINESACCOUNTEDDR AS NUMERIC), 2),0) !=0  OR IFNULL(ROUND(CAST(GJL.GLJELINESACCOUNTEDCR AS NUMERIC), 2),0) !=0)
				
;
END;