CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_TRANSACCIONES_CUENTAS_A_COBRAR()
BEGIN

	CREATE OR REPLACE TABLE amrl-data-prd.PRESENTATION.FACT_TRANSACCIONES_CUENTAS_A_COBRAR PARTITION BY
   FH_TRANSACCION   AS 
  
	/**************************** Tabla de hechos del modulo de cuentas a cobrar, aca se relacionan las tablas requeridas de la capa RAW y las llaves necesarias para crear la tabla consolodada en en la capa de presentacion    ***************************/
  	SELECT 
			222 APPLICATIONID,
			'TRANSACTIONS' ORIGEN,
			SHA256(CAST(RCTA.RACUSTOMERTRXCUSTOMERTRXID AS STRING)) SK_IDORIGEN,
			RCTA.RACUSTOMERTRXCUSTOMERTRXID BK_IDORIGEN,
			SHA256(CAST(RCTA.RACUSTOMERTRXBILLTOCUSTOMERID AS STRING)) SK_TERCERO,
			RCTA.RACUSTOMERTRXBILLTOCUSTOMERID BK_TERCERO,
			RCTA.RACUSTOMERTRXTRXNUMBER DOCUMENTO,
			RACUSTOMERTRXTRXDATE FH_TRANSACCION
		FROM 
		amrl-data-prd.RAW.FUSION_RA_CUSTOMER_TRX_ALL RCTA;
		END;