CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_FACT_TRACKING_ESCRITURACION()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla FACT_TRACKING_ESCRITURACION. Este SP unifica en una tabla maestra los proceso gestionados por los equipos de escrituración (legalización, ordendes, escrituración, creditos, subsidios y entregas) en la herramienta TRACKING TOOLS")
BEGIN

CREATE OR REPLACE TABLE `amrl-data-prd.PRESENTATION.FACT_TRACKING_ESCRITURACION` PARTITION BY
  FESC CLUSTER BY OP AS

   SELECT       /********************************************* Proceso de legalizacion ***********************************************************/
                A.OP                                           AS OP,
                A.GesCred                                      AS GESCRED,
                C.Est_Sup                                      AS EST_SUP,
                C.Est_Ana                                      AS EST_ANA,
                C.Obs_Ana                                      AS OBS_ANA_LEGALIZACION,
                C.Obs_Sup                                      AS OBS_SUP,
                C.Analista_Leg                                 AS ANALISTA_LEG,
                C.Analista                                     AS ANALISTA,
                A.CIUDAD                                       AS CIUDAD,
                A.TIPO_DE_PROYECTO                             AS T_PROYECTO,
                A.MACROCONSOLIDADOR                            AS PROYECTO,
                A.TRANSACCIONAL                                AS ETAPA,
                A.ValorTotal                                   AS V_TOTAL,
                A.INMUEBLE_PRINCIPAL                           AS INMUEBLE,
                A.Torre                                        AS TORRE,
                A.Apto                                         AS APTO,
                A.COMPRADOR1                                   AS COM_PRINCIPAL,
                A.IDENTIFICACION_COMPRADOR1                    AS CC_PRINCIPAL,
                A.COMPRADOR2                                   AS COM_ALTERNOS,
                A.IDENTIFICACION_COMPRADOR2                    AS CC_ALTERNOS,
                C.Cli_Exterior                                 AS CLI_EXTERIOR,
                C.Apoderado                                    AS APODERADO, 
                C.Apoderado_Cel                                AS APODERADO_CEL,
                C.Apoderado_Correo                             AS APODERADO_CORREO,
                A.TELEFONO_COMPRADOR1                          AS CEL_PRINCIPAL,
                A.EMAIL_COMPRADOR1                             AS CORREO_PRINCIPAL,
                A.TELEFONO_COMPRADOR2                          AS CEL_ALTERNOS,
                A.EMAIL_COMPRADOR2                             AS CORREO_ALTERNOS,
                A.TIPO_VENTA                                   AS TIPO_V,
                C.CambioTipo_V                                 AS CAMBIOTIPO_V,
                A.ENTIDAD_CREDITO                              AS ENT_CRED,
                A.MONTO_CREDITO                                AS V_CRED,
                A.ENTIDAD_SUBSIDIO_1                           AS ENT_SUB1,
                A.MONTO_SUBSIDIO_1                             AS V_SUB1,
                A.ENTIDAD_SUBSIDIO_2                           AS ENT_SUB2,
                A.MONTO_SUBSIDIO_2                             AS V_SUB2,
                C.Ent_Sub3                                     AS ENT_SUB3,
                C.V_Sub3                                       AS V_SUB3,
                C.Ent_Sub4                                     AS ENT_SUB4,
                C.V_Sub4                                       AS V_SUB4, 
                C.Est_Otros_Sub                                AS EST_OTROS_SUB,
                B.CuotaInicial                                 AS C_INICIAL_PAC,
                A.BSTR,
                A.RVDF,
                A.ACAV,
                A.VCAV,
                A.ASUB,
                A.VSUB,
                A.ASMY,
                A.ARSC,
                A.FPRC,
                A.EPP5,
                C.Env_Titulacion                               AS ENV_TITULACION,               
                C.Sisb_Comp                                    AS SISB_COMP,
                C.Sisb_Otro                                    AS SISB_OTRO,
                C.Est_MCY                                      AS EST_MCY,
                A.OCNO                                         AS OCNO,
                A.LTCN                                         AS LTCN,
                A.Dias_CF                                      AS DIAS_CF,  
                C.Sol_Ava_Tipo                                 AS SOL_AVA_TIPO,
                C.Rec_Ava_Tipo                                 AS REC_AVA_TIPO,                 
                A.RNOV                                         AS RNOV,
                A.ANOV                                         AS ANOV,
                A.RLEG                                         AS RLEG,
                A.Dias_RLEG                                    AS DIAS_RLEG, 
                A.ALEG                                         AS ALEG,
                A.Dias_ALEG                                    AS DIAS_ALEG, 
                A.VLEG                                         AS VLEG,
                A.Dias_VLEG                                    AS DIAS_VLEG,
                C.Leg_Varada                                   AS LEG_VARADA,
                A.LNEG                                         AS LNEG,
                C.VOBO_Min_Leas                                AS VOBO_MIN_LEAS,
                C.Age_Firm_Pagares                             AS AGE_FIRM_PAGARES,
                C.Fir_Paga_Seguros                             AS FIR_PAGA_SEGUROS,
                C.Uni_Desistimiento                            AS UNI_DESISTIMIENTO,
                B._PagadoCI                                    AS `%PAGADO`, 
                B.FechaUltmCuotaCI                             AS FEC_ULTM_CI,
                B.PendientePagoCI                              AS PEN_PAGOCI,
                B.Dmora                                        AS D_MORA_,
                B.FechaUltimaCuotaMora                         AS FEC_MORA,
                B.RXmora                                       AS ESTATUS_MORA,
                B.ValorUltmCuota                               AS VAL_ULTM_CUOTA, 
                B.CuotasPendientes                             AS CUO_PENDIENTES, 
                B.ValorCuotas                                  AS VAL_CUOTAS, 
                B.AhorroProgramado                             AS AHO_PROGRAMADO,
                B.Cesantias                                    AS CESANTIAS,
                B.CuentasAFC                                   AS AFC,
                B.PensionesVoluntarias                         AS PEN_VOLUNT,
                C.VBOE                                         AS VBOE, 
                A.AFEC                                         AS AFEC,
                A.Dias_Citacion                                AS DIAS_CITACION,
                C.FESC                                         AS FESC,
                A.Est_Nego_Sistema                             AS EST_NEGO_SISTEMA, 
                A.FECHA_PROYECTADA_ESCRITURACION               AS MET_PLAN_FINAN,
                C.Met_Int_Neg                                  AS MET_INT_NEG,
                C.Met_Escrituracion                            AS MET_ESCRITURACION,
                A.FECHA_PROYECTADA_CTO                         AS PROYE_CTO, 
                A.FECHA_REAL_CTO                               AS CTO,
                A.FECHA_PROYECTADA_RPH                         AS PROYE_RPH,
                A.FECHA_REAL_RPH                               AS RPH, 
                --`%Ava_Obra`, --NO DISPONIBLE
                C.Pol_Decenal                                  AS POL_DECENAL,
                --Fec_Entrega,
                --Hab_Entrega,
                A.BANCO_CONSTRUCTOR                            AS BAN_CONSTRUCTOR,
                E.Est_Cred_Constructor                         AS EST_CRED_CONSTRUCTOR, 
                A.NOTARIA                                      AS NOT_NOTARIA,
                A.Ava_Estu_Titulos                             AS AVA_ESTU_TITULOS,
                A.Imp_Timbre                                   AS IMP_TIMBRE,
                A.Notariales                                   AS NOTARIALES,
                A.Tot_Gobernacion                              AS TOT_GOBERNACION,
                A.Registro                                     AS REGISTRO,
                A.Sistematizacion                              AS SISTEMATIZACION,
                A.Tot_Registro                                 AS TOT_REGISTRO,
                A.Tot_GyR                                      AS TOT_GYR,
                A.Tot_Gastos                                   AS TOTALGASTOS,
                C.Est_Gest_Cart                                AS EST_GEST_CART,
                C.Obs_Gest_Cartera                             AS OBS_GEST_CARTERA,
                C.Supervisor                                   AS SUPERVISOR,   
                A.DIRECTOR_DE_VENTAS_VIVIENDAS_TRANSACCIONAL   AS DIRECTOR,
                A.Listo_para_Esc                               AS LISTO_PARA_ESC,
                C.Fec_Citacion                                 AS FEC_CITACION,
                C.Hor_Citacion                                 AS HOR_CITACION,         
                /********************************************* Proceso de Ordenes ***********************************************************/
                A.Zona                                         AS ZONA,
                D.Analista                                     AS ANALISTA_ORDENES, 
                D.Paz_Salvo                                    AS PAZ_SALVO,
                A.Est_Gral                                     AS EST_GRAL,
                A.NUMERO_DE_ESCRITURA                          AS NO_ESCRITURA,
                A.No_Matricula                                 AS NO_MATRICULA,                
                A.Ctrl_Citacion                                AS CTRL_CITACION,
                D.Obs_Ana                                      AS OBS_ANA_ORDENES,        
                D.Sub_Estado                                   AS SUB_ESTADO,
                --C.Analista_Ord,
                A.SALA_DE_VENTAS                               AS SALA_DE_VENTAS,
                A.Est_IDU                                      AS EST_IDU,
                D.Fec_Sol_IDU                                  AS FEC_SOL_IDU,
                D.Fec_Venc_IDU                                 AS FEC_VENC_IDU,
                D.Tipo_Predial                                 AS TIPO_PREDIAL,
                D.Est_Predial                                  AS EST_PREDIAL,  
                /********************************************* Recorrido de Escrituración ***********************************************************/
                A.Est_Recorrido                                AS EST_RECORRIDO,
                A.Fec_Est_Rdo                                  AS FEC_EST_RDO,
                A.Dias_Est_Rdo                                 AS DIAS_EST_RDO,
                A.Obs_Est_Rdo                                  AS OBS_EST_RDO,
                A.Dias_Rdo_Esc_Fda                             AS DIAS_RDO_ESC_FDA,
                A.Obs_Rdo_Esc_Fda                              AS OBS_RDO_ESC_FDA,
                A.Grupo_Entidad                                AS GRUPO_ENTIDAD,
                A.Fec_Prort_Cta_Comp                           AS FEC_PRORT_CTA_COMP,
                E.Observacion                                  AS OBSERVACION,
                E.Responsable                                  AS RESPONSABLE,
                E.Comentario                                   AS COMENTARIO,
                A.SAVA,                                          
                A.LLAV,
                D.OESV,                
                E.SCCM,
                E.LLCM,
                E.EACC,
                E.VBCC,
                E.LLES,
                E.ECNT,
                E.LCRN,
                E.EEFA,
                E.SPPT,
                E.PPPT,
                E.EFLB,
                E.EEFB,
                E.ECBN,
                E.EEB2,
                E.REHP,
                E.FRES,
                E.EACN,
                E.LLCN,
                E.IREG,
                E.CRR1,
                E.CRR2,
                E.SDER,
                E.CIVA,
                A.EIRE,
                A.EACT,
                A.ADSC,
                E.FEGB,
                E.CLCR,
                A.RASB,
                A.ADMY,
                A.ECSV,
                E.Mtd_Aplicacion                                AS MTD_APLICACION,
                A.Est_Flj_Caja                                  AS EST_FLJ_CAJA,
                E.Val_Prorrata                                  AS VAL_PRORRATA,
                E.Est_Entrega_Inm                               AS EST_ENTREGA_INM,
                E.Desembolsado                                  AS DESEMBOLSADO,
                A.Rdo_Comite                                    AS RDO_COMITE,
                A.Dias_Liberacion                               AS DIAS_LIBERACION,
                A.Dias_Banco                                    AS DIAS_BANCO     
        FROM `RAW_TRACKING_TOOLS.TT_GLOBAL` AS A
        LEFT JOIN `RAW_TRACKING_TOOLS.TT_GLOBAL_RECAUDO` AS B ON A.OP = B.OP
        LEFT JOIN `RAW_TRACKING_TOOLS.TT_LEGALIZACION` AS C ON B.OP=C.OP
        LEFT JOIN `RAW_TRACKING_TOOLS.TT_ORDENES` AS D ON A.OP = D.OP 
        LEFT JOIN `RAW_TRACKING_TOOLS.TT_RECORRIDO_DE_ESCRITURACION` AS E ON A.OP = E.OP;

 
END;