CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_DIM_MACROCONSOLIDADOR()
OPTIONS(
  description="Propósito: Crear y actualizar la tabla DIM_MACROCONSOLIDADOR, consolidando todos los atributos que corresponden al macro MACROCONSOLIDADOR de cada proyecto, esta tabla se crea con el proposito de relacionar las metas comerciales y financieras en los diferentes momentos y jerarquias\nAutor: Maria Fernanda Franco")
BEGIN

CREATE TEMP TABLE TEMP_MACROCONSOLIDADOR AS
( 	
    SELECT 
           ROW_NUMBER() OVER (ORDER BY SK_COD_MACROCONSOLIDADOR) AS ID_DIM_MACROCONSOLIDADOR
          ,SK_COD_MACROCONSOLIDADOR
          ,MACROCONSOLIDADOR
          ,FECHA_ACTUALIZACION_BQ
          ,FECHA_CARGUE_BQ
    FROM (
            SELECT ROW_NUMBER() OVER (PARTITION BY FTN.PARENTPK1VALUE ORDER BY FTN.W_CREATE_DT DESC) AS SK_OBT_FACT_OPORTUNIDAD
                  ,FTN.PARENTPK1VALUE AS SK_COD_MACROCONSOLIDADOR
                  ,FVV.DESCRIPTION            AS MACROCONSOLIDADOR
                  --,DSE.BK_COD_TRANSACCIONAL AS BK_COD_TRANSACCIONAL   
                  ,FTN.W_UPDATE_DT            AS FECHA_ACTUALIZACION_BQ
                  ,FTN.W_CREATE_DT            AS FECHA_CARGUE_BQ      
            FROM `RAW.FUSION_FND_TREE_NODE` AS FTN 
            LEFT JOIN `RAW.FUSION_FND_FLEX_VALUES_VL` AS FVV ON  FVV.FLEX_VALUE =FTN.PARENTPK1VALUE
            WHERE FTN.TREECODE ='FCR_GA_PROYECTOS' AND FTN.PARENTPK1VALUE IS NOT NULL AND FVV.DESCRIPTION  IS NOT NULL )
    WHERE SK_OBT_FACT_OPORTUNIDAD = 1
            
);


--CREANDO TABLA PERMANENTE
--CREATE OR REPLACE TABLE `amrl-data-prd.PRESENTATION.DIM_MACROCONSOLIDADOR` AS 
--SELECT * FROM TEMP_MACROCONSOLIDADOR;

    MERGE   PRESENTATION.DIM_MACROCONSOLIDADOR     AS T
    USING   (SELECT * FROM TEMP_MACROCONSOLIDADOR) AS S
    ON      (T.SK_COD_MACROCONSOLIDADOR = S.SK_COD_MACROCONSOLIDADOR)
    WHEN MATCHED THEN
    UPDATE SET  T.MACROCONSOLIDADOR               = S.MACROCONSOLIDADOR,
                T.FECHA_ACTUALIZACION_BQ     = CURRENT_DATETIME("America/Bogota")
    WHEN NOT MATCHED THEN
    INSERT  (   ID_DIM_MACROCONSOLIDADOR,
                SK_COD_MACROCONSOLIDADOR, 
                MACROCONSOLIDADOR,
                FECHA_ACTUALIZACION_BQ,               
                FECHA_CARGUE_BQ               
            )
    VALUES (    S.ID_DIM_MACROCONSOLIDADOR,
                S.SK_COD_MACROCONSOLIDADOR, 
                S.MACROCONSOLIDADOR,
                S.FECHA_ACTUALIZACION_BQ,               
                S.FECHA_CARGUE_BQ
            );

END;