CREATE PROCEDURE `amrl-data-prd`.MONITORING.SP_TBL_DETALLE_ACTUALIZACION_RAW()
BEGIN


CREATE OR REPLACE TABLE `amrl-data-prd.MONITORING.TBL_DETALLE_ACTUALIZACION_RAW`
AS
WITH ACTUALIZACION_RAW AS 
(
SELECT  
SK_DETALLE_TABLA,
DATASET,
TABLA,
FECHA,
TOTAL_FILAS,
LAG(TOTAL_FILAS) OVER (PARTITION BY DATASET, TABLA ORDER BY FECHA) AS FILAS_DIA_ANTERIOR,
FECHA_ULTIMA_MODIFICACION
FROM `MONITORING.TBL_HISTORICO_ACTUALIZACION_RAW`
)

SELECT
SK_DETALLE_TABLA,
DATASET,
TABLA,
FECHA,
TOTAL_FILAS,
FILAS_DIA_ANTERIOR,
(TOTAL_FILAS - FILAS_DIA_ANTERIOR) AS FILAS_CARGADAS,
CASE WHEN ABS (TOTAL_FILAS - FILAS_DIA_ANTERIOR) > 0 THEN 1 ELSE 0 END AS MOVIMIENTO_DIARIO,
FECHA_ULTIMA_MODIFICACION
FROM ACTUALIZACION_RAW;



END;