CREATE PROCEDURE `amrl-data-prd`.OPERATIONAL.SP_OBT_FACT_HISTORICO_DE_VENTAS()
OPTIONS(
  description="Propósito: generar una copia de la tabla OBT_FACT_OPORTUNIDAD unicamente el ultimo dia de cada mes, con el objetivo de guardar una instantanea del cierre de ventas mensual")
BEGIN
  DECLARE fecha_actual DATE;
  DECLARE ultimo_dia_mes DATE;

  SET fecha_actual = CURRENT_DATE();
  SET ultimo_dia_mes = DATE_SUB(DATE_ADD(DATE_TRUNC(fecha_actual, MONTH), INTERVAL 1 MONTH), INTERVAL 1 DAY);     

  -- Validar si es último día del mes
  IF fecha_actual = ultimo_dia_mes THEN   

   -- Insertar los datos con fecha y hora actual
    EXECUTE IMMEDIATE """
      INSERT INTO `amrl-data-prd.CONSUMPTION.OBT_FACT_HISTORICO_DE_VENTAS`
      SELECT SK_OBT_FACT_OPORTUNIDAD
            ,BK_COD_MACROPROYECTO
            ,MACROPROYECTO
            ,SK_COD_MACROCONSOLIDADOR
            ,MACROCONSOLIDADOR
            ,SK_COD_TRANSACCIONAL
            ,TRANSACCIONAL
            ,SALA_DE_VENTAS
            ,SALA_DE_VENTAS_ALTERNATIVA
            ,TIPO_DE_PROYECTO
            ,ESTADO_PROYECTO
            ,CIUDAD
            ,DIRECCION_PROYECTO
            ,BANCO_CONSTRUCTOR
            ,ENTIDAD_FIDUCIARIA
            ,DIRECTOR_DE_VENTAS_VIVIENDAS_TRANSACCIONAL
            ,DIRECTOR_DE_VENTAS_COMERCIOS_TRANSACCIONAL
            ,FECHA_INICIO_VENTAS_TRANSACCIONAL
            ,FECHA_PUNTO_DE_EQUILIBRIO
            ,FECHA_PROYECTADA_RPH
            ,FECHA_REAL_RPH
            ,SK_OP
            ,BK_NUMERO_OP
            ,NOMBRE_OP
            ,METODO_DE_VENTAS
            ,ETAPA_DE_VENTA
            ,IMPORTE_TOTAL_OP
            ,IMPORTE_TOTAL_OP_PRIMERA_VERSION
            ,INMUEBLE_PRINCIPAL
            ,BK_VENDEDOR
            ,NOMBRE_VENDEDOR
            ,OP_CREADA_POR
            ,FECHA_DE_CREACION_OP
            ,OP_ACTUALIZADA_POR
            ,FECHA_ULTIMA_ACTUALIZACION_OP
            ,ACEPTAR_VENTA
            ,TIPO_VENTA
            ,DESTINO
            ,REFERIDO
            ,OBSERVACIONES
            ,PORCENTAJE_COMPRADORES
            ,FECHA_DE_SEPARACION
            ,FECHA_DE_SEPARACION_AJUSTADA
            ,FECHA_COMPROMISO_RADICACION_CREDITO
            ,FECHA_COMPROMISO_RADICACION_SUBSIDIO
            ,INMUEBLE_OPCIONADO
            ,ENTIDAD_CREDITO
            ,MONTO_CREDITO
            ,ENTIDAD_CREDITO_TER_1
            ,MONTO_CREDITO_TER_1
            ,ENTIDAD_CREDITO_TER_2
            ,MONTO_CREDITO_TER_2
            ,ENTIDAD_SUBSIDIO_1
            ,MONTO_SUBSIDIO_1
            ,ENTIDAD_SUBSIDIO_2
            ,MONTO_SUBSIDIO_2
            ,PUNTO_DE_EQUILIBRIO
            ,BLOQUEO
            ,NUMERO_DE_ESCRITURA
            ,FECHA_DE_ESCRITURA
            ,NOTARIA
            ,CIRCULO_NOTARIAL
            ,DESISTIDO
            ,FECHA_DESISTIDO
            ,FECHA_DESISTIDO_AJUSTADA
            ,FECHA_RADICADO_DOCUMENTOS_DESISTIMIENTO
            ,CAUSA_DESISTIMIENTO
            ,TIPO_DESISTIMIENTO
            ,OBSERVACION_DESISTIMIENTO
            ,BK_PERSONA
            ,BK_OP_CDA
            ,COMPRADOR1
            ,IDENTIFICACION_COMPRADOR1
            ,FECHA_DE_NACIMIENTO_COMPRADOR1
            ,PAIS_COMPRADOR1
            ,CIUDAD_COMPRADOR1
            ,DIRECCION_COMPRADOR1
            ,EMAIL_COMPRADOR1
            ,TELEFONO_COMPRADOR1
            ,GENERO_COMPRADOR1
            ,ESTADO_CIVIL_COMPRADOR1
            ,OCUPACION_COMPRADOR1
            ,BK_COMPRADOR2
            ,COMPRADOR2
            ,IDENTIFICACION_COMPRADOR2
            ,FECHA_DE_NACIMIENTO_COMPRADOR2
            ,PAIS_COMPRADOR2
            ,CIUDAD_COMPRADOR2
            ,DIRECCION_COMPRADOR2
            ,EMAIL_COMPRADOR2
            ,TELEFONO_COMPRADOR2
            ,GENERO_COMPRADOR2
            ,ESTADO_CIVIL_COMPRADOR2
            ,OCUPACION_COMPRADOR2
            ,BK_ARTICULO
            ,NOMBRE_ARTICULO
            ,CATEGORIA
            ,REFERENCIA
            ,ESTADO_DEL_ARTICULO
            ,CLASE_DE_ARTICULO
            ,PRECIO_UNITARIO
            ,CAST(AREA_CONSTRUIDA AS STRING) AS AREA_CONSTRUIDA
            ,AREA_COMUN
            ,FECHA_PROYECTADA_ESCRITURACION
            ,FECHA_PROYECTADA_CTO
            ,FECHA_REAL_CTO
            ,FECHA_PROYECTADA_POLIZA_DECENAL
            ,FECHA_REAL_POLIZA_DECENAL
            ,BK_OP
            ,BSTR
            ,RVDF
            ,ASUB
            ,VSUB
            ,ASMY
            ,VSMY
            ,ARSC
            ,ACAV
            ,VCAV
            ,AOCR
            ,ACDS
            ,VCDS
            ,FPRC
            ,EPP5
            ,SAVA
            ,LLAV
            ,RNOV
            ,ANOV
            ,RLEG
            ,LNEG
            ,ALEG
            ,VLEG
            ,OESV
            ,PSCA
            ,SCCM
            ,LLCM
            ,EACC
            ,ACCC
            ,FESC
            ,LLES
            ,ECNT
            ,LCRN
            ,EEFA
            ,LLEA
            ,SPPT
            ,PPPT
            ,EFLB
            ,LLFL
            ,EEFB
            ,LLEB
            ,EACN
            ,LLCN
            ,SCHE
            ,REPG
            ,ECEG
            ,IREG
            ,SRE1
            ,CRR1
            ,SRE2
            ,CRR2
            ,SDER
            ,CIVA
            ,EIRE
            ,EACT
            ,ISPH
            ,SHAB
            ,LHAB
            ,AS80
            ,AS20
            ,ADSU
            ,ADSC
            ,FEGB
            ,CLCR
            ,RASB
            ,RADS
            ,ADMY
            ,ECSV
            ,SUBR
            ,NCAV
            ,DSUB
            ,ODSE
            ,APRE
            ,FENC
            ,EGAE
            ,RCAV
            ,EFCO
            ,AMFN
            ,LENT
            ,OCNO
            ,RMFN
            ,EGA2
            ,DESE
            ,ETGB
            ,EPRO
            ,ROCR
            ,LLCG
            ,LLPT
            ,LMHF
            ,LLST
            ,EPRV
            ,EPP1
            ,EPP2
            ,EPP3
            ,EPP4
            ,LLAP
            ,PEQU
            ,SLCC
            ,SCAF
            ,EPRA
            ,ECFL
            ,LLGA
            ,SMHF
            ,SNRF
            ,ANRF
            ,DSMY
            ,EFSV
            ,PSLB
            ,RSMY
            ,EEB2
            ,ELNR
            ,VCOE
            ,DNRF
            ,ECBN
            ,EDNR
            ,LLCA
            ,LCNB
            ,LLPA
            ,EIPR
            ,RACH
            ,VOCN
            ,EVBA
            ,FPEF
            ,FAPA
            ,SPVP
            ,VBOE
            ,FPDC
            ,ENCH
            ,EISC
            ,RPSU
            ,LTCN
            ,SRPF
            ,CIEL
            ,DS20
            ,DS80
            ,ECAP
            ,EENF
            ,EENS
            ,EPEF
            ,FPVS
            ,LPMJ
            ,DGSV
            ,EAMS
            ,ICGR
            ,LACF
            ,LLEF
            ,LRCG
            ,FPOC
            ,EEFF
            ,LLVB
            ,LFCN
            ,OCNP
            ,RGPB
            ,EOEN
            ,SRPH
            ,DEBC
            ,DPCN
            ,EPPE
            ,LPPE
            ,SACF
            ,FOCN
            ,FANC
            ,FPCB
            ,LCVV
            ,RSUB
            ,EEPM
            ,LCEC
            ,LPMA
            ,TPVM
            ,VTPM
            ,EDAP
            ,FAPF
            ,SCEG
            ,FPPE
            ,LDMF
            ,OKNC
            ,RVCF
            ,AACH
            ,DOEV
            ,LPMF
            ,PEHB
            ,DVCF
            ,EPMA
            ,FCAP
            ,FOMI
            ,RVCV
            ,VACH
            ,VOCR
            ,EVPE
            ,APCF
            ,EBPG
            ,SVCN
            ,FTPM
            ,LFPE
            ,CICV
            ,VPCF
            ,SVMI
            ,EPCF
            ,EMCF
            ,FAMI
            ,FRAM
            ,LTPM
            ,VRAM
            ,EVDV
            ,EFPE
            ,EFCF
            ,LPCF
            ,LOMI
            ,LRAM
            ,RAVM
            ,EPOC
            ,LMCF
            ,EOCF
            ,LPOC
            ,LOCF
            ,FRES
            ,RDES
            ,LFH2
            ,OMCY
            ,SDES
            ,LMCY
            ,RZMT
            ,EEAR
            ,RMTP
            ,PSUB
            ,EFH2
            ,RAC2
            ,REHP
            ,VBCC
            ,LPSB
            ,LLMN
            ,NIFP
            ,CIFL
            ,EPMJ
            ,SVMS
            ,AFEC
            ,ASMP
            ,DRAO
            ,EFPA
            ,FECS
            ,LEOC
            ,LFAP
            ,RAO2
            ,LFMS
            ,ARTC
            ,DRAC
            ,DADS
            ,EFCS
            ,EEFO
            ,MSEF
            ,FNAE
            ,NDVC
            ,LTNP
            ,CNEF
            ,EVCA
            ,ECNF
            ,ADS2
            ,DSVA
            ,LTMS
            ,CAVF
            ,LPET
            ,EPEV
            ,EEPF
            ,CAEF
            ,EVB2
            ,LFNP
            ,FCNP
            ,LFPA
            ,FECN
            ,VONP
            ,FEPE
            ,SK_FECHA
            ,FECHA
            ,ANIO
            ,NUM_TRIMESTRE
            ,NUM_MES
            ,NUM_SEMANA
            ,NUM_DIA
            ,NUM_DIA_SEMANA
            ,NOM_TRIMESTRE
            ,NOM_MES_INGLES
            ,NOM_MES_ESP
            ,NOM_DIA_SEMANA_ING
            ,NOM_DIA_SEMANA_ESP
            ,FISCAL_YEAR_T1
            ,FISCAL_PERIOD_T1
            ,FISCAL_QUARTER_T1
            ,FUENTE
            ,FECHA_ACTUALIZACION_BQ
            ,FECHA_CARGUE_BQ
            ,CURRENT_TIMESTAMP() AS FECHA_DE_CIERRE
      FROM `CONSUMPTION.OBT_FACT_OPORTUNIDAD`
    """;

    --Imprime los valores de fecha actual y ultimo dia del mes.
     SELECT fecha_actual,ultimo_dia_mes;
    
  END IF; 
  

END;